### ISSUE TITLE
An error occured while attempting to reach API

### ISSUE THREAD

**Issue by blackPantherOS** [ProtonVPN/linux-cli#10]
Hi,

We got this message after tried login and enter password
```

Enter your ProtonVPN password: 

An error occured while attempting to reach API
```

**Comment by lennyalderson** [comment]
The same here. been like this for about a month now. I've had this issue before  with the previous protonvpn command lines. probably has to do with protonvpn being blocked in my country [Iran].

**Comment by calexandru2018** [comment]
Hey @blackPantherOS 

Can you ping api.protonvpn.ch ? If not then is indeed as @lennyalderson is stating. We're currently working on alternative routing, so this shouldn't be happening once alternative routing is complete.

**Comment by Graham1384** [comment]
when alternative routing will be available? protonvpn-cli-ng app told me to upgrade to 3.7.1 version of protonvpn-cli and now I can't change from protonvpn.ch to protonmail.ch!

**Comment by ghonchesefidi** [comment]
I have same problem

**Comment by Graham1384** [comment]
> I have same problem

It's about 3 months I posted my comment and they didn't add the alternative routing. It's available on their mobile app but takes time to migrate it to Linux. At the moment you'd rather use protonvpn-cli-ng from AUR if you are in arch. It's still maintained and works fine.

**Comment by calexandru2018** [comment]
Hey @Graham1384 , @ghonchesefidi , @lennyfrost  and  @blackPantherOS . Alternative routing is now available in early access. If you would like to try it out, select your distro from here and follow the steps to install early access (aka beta) version.

Please provide some feedback here or (preferably) to our support.

**Comment by ghonchesefidi** [comment]
@calexandru2018 Thanks for your update. I have followed the link and was able to install the beta version and it's working fine for me now. 
Appreciate your help.

**Comment by calexandru2018** [comment]
Alternative routing has been pushed to stable branch, and that includes AUR. Please provide feedback if alternative routing did work, and if so close this issue.

**Comment by Graham1384** [comment]
> Alternative routing has been pushed to stable branch, and that includes AUR. Please provide feedback if alternative routing did work, and if so close this issue.

thanks, It's working now on Manjaro. really faster than the ng version.

**Comment by Graham1384** [comment]
> Alternative routing has been pushed to stable branch, and that includes AUR. Please provide feedback if alternative routing did work, and if so close this issue.

oops. I think I was mistaken. the first time I logged in I used my mobile data and now I'm using wifi to connect. It seems when I choose country the CLI crashes and gets stuck here.

![image](https://user-images.githubusercontent.com/62774242/134653324-fcd6d117-e741-42e1-93e9-e3984940ee16.png)

this is where I always get stuck on official CLI. I don't think alternative routing is working.
sorry for the first reply. I had to test it more precisely.

**Comment by Graham1384** [comment]
I had to test it more precisely. when I try to log in via wifi. I get this message:
HTTPSConnectionPool(host='dns11.quad9.net', port=443): Read timed out. (read timeout=3.05)

sorry for the first reply.

**Comment by calexandru2018** [comment]
@Graham1384 can you reach out to support ?

**Comment by Graham1384** [comment]
> @Graham1384 can you reach out to support ?
> 
> So login works from mobile data but not wifi ?

yes

**Comment by Graham1384** [comment]
> @Graham1384 can you reach out to support ?
> 
> So login works from mobile data but not wifi ?

after restarting the laptop the connection itself won't work. it gets stuck here:

![image](https://user-images.githubusercontent.com/62774242/134677205-63b04eac-31d1-424b-ae20-10115d8cc61c.png)

**Comment by Graham1384** [comment]
@calexandru2018 should I install the community version or a fix will be available soon?

**Comment by calexandru2018** [comment]
@Graham1384 please contact support as we need to debug and understand what is happening.

**Comment by aliazani** [comment]
@calexandru2018 I did that too but not still not working!
I got HTTPSConnectionPool(host='dns11.quad9.net', port=443): Read timed out. (read timeout=3.05)

**Comment by calexandru2018** [comment]
@aliazani please reach out to support

**Comment by Graham1384** [comment]
@calexandru2018 
@aliazani 

I think I've found a workaround by accident

1. first change dns to 1.1.1.1
2. then connect to mobile hotspot. (one that can ping protonvpn.ch)
3. now login to your account using cli
4. then connect to any network you want and connect to VPN

It worked for me. try it out!

**Comment by calexandru2018** [comment]
@Graham1384 with alt routing this shouldn't be necessary. If alt routing is not working for you, please reach out to customer support so we can gather more info and make sure that alternative routing is working for you (and others that are in a similar situation)

**Comment by calexandru2018** [comment]
Hey @aliazani and @Graham1384 , the situation was identified and a patch will be pushed next beta release. The issue was that the exception was not being catched, thus not allowing to loop through the available DNSs. 

Make sure you have the beta version installed to receive the latest versions and test it out.

**Comment by aliazani** [comment]
@calexandru2018 Great, let us know when it was available.

**Comment by Yugeniki** [comment]
For whatever it is worth, two months later the issue persists still, for me at least.
Can't log into protonvpn, but in my case the issue is "unknown error occured". My country is the same as others here, Iran. So it is probably being blocked yet again.

**Comment by pmoieni** [comment]
> For whatever it is worth, two months later the issue persists still, for me at least. Can't log into protonvpn, but in my case the issue is "unknown error occured". My country is the same as others here, Iran. So it is probably being blocked yet again.

It's the same for everyone here. seems they need to change something on the server side. for now there's no chance for it to get fixed. BTW this command works at least:

> protonvpn-cli c -f

It takes about 30 seconds to find the fastest server and connect but after establishing connection you can run "protonvpn-cli c" again to connect to your prefered server.

programming without a VPN is such a mess.😔

**Comment by aliazani** [comment]
@calexandru2018 After long period of time, I've tested official version again but now I'm facing Network error with alternate routing enable like below:

> 2022-06-04 08:17:28,967 — cli.py — INFO — __init__:29 — Proton VPN CLI v3.12.0 (protonvpn-nm-lib v3.10.0; proton-client v0.7.1)
> 2022-06-04 08:17:28,969 — cli.py — INFO — __init__:64 — CLI command: Namespace(command='login', version=False, help=False, get_logs=False)
> 2022-06-04 08:17:33,671 — cli_wrapper.py — INFO — login:68 — Credentials provided, attempting to login
> 2022-06-04 08:18:37,365 — cli_wrapper.py — ERROR — login:117 — Network error
> Traceback (most recent call last):
>   File "/usr/lib/python3.10/site-packages/protonvpn_cli/cli_wrapper.py", line 73, in login
>     self.protonvpn.login(username, password)
>   File "/usr/lib/python3.10/site-packages/protonvpn_nm_lib/api.py", line 36, in login
>     self._env.api_session.authenticate(username, password, human_verification)
>   File "/usr/lib/python3.10/site-packages/protonvpn_nm_lib/core/session/session.py", line 39, in __call__
>     result = self._func(session, *args, **kwargs)
>   File "/usr/lib/python3.10/site-packages/protonvpn_nm_lib/core/session/session.py", line 390, in authenticate
>     self.__proton_api.authenticate(username, password)
>   File "/usr/lib/python3.10/site-packages/proton/api.py", line 387, in authenticate
>     info_response = self.api_request("/auth/info", payload)
>   File "/usr/lib/python3.10/site-packages/proton/api.py", line 261, in api_request
>     response = self.__try_with_alt_routing(fct, **request_params)
>   File "/usr/lib/python3.10/site-packages/proton/api.py", line 327, in __try_with_alt_routing
>     raise NetworkError("Network error")
> proton.exceptions.NetworkError: Network error

And without alternate routing I face Unable to reach API like below:

> 2022-06-04 08:15:38,701 — cli.py — INFO — __init__:29 — Proton VPN CLI v3.12.0 (protonvpn-nm-lib v3.10.0; proton-client v0.7.1)
> 2022-06-04 08:15:38,702 — cli.py — INFO — __init__:64 — CLI command: Namespace(command='login', version=False, help=False, get_logs=False)
> 2022-06-04 08:15:39,798 — cli_wrapper.py — INFO — login:68 — Credentials provided, attempting to login
> 2022-06-04 08:16:08,975 — cli_wrapper.py — ERROR — login:93 — Unable to reach API
> Traceback (most recent call last):
>   File "/usr/lib/python3.10/site-packages/protonvpn_nm_lib/core/session/session.py", line 39, in __call__
>     result = self._func(session, *args, **kwargs)
>   File "/usr/lib/python3.10/site-packages/protonvpn_nm_lib/core/session/session.py", line 390, in authenticate
>     self.__proton_api.authenticate(username, password)
>   File "/usr/lib/python3.10/site-packages/proton/api.py", line 387, in authenticate
>     info_response = self.api_request("/auth/info", payload)
>   File "/usr/lib/python3.10/site-packages/proton/api.py", line 256, in api_request
>     raise exception_class(exception_msg)
> proton.exceptions.NewConnectionError: TLSPinningHTTPSConnectionPool(host='api.protonvpn.ch', port=443): Max retries exceeded with url: /auth/info (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fc911e0ded0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/usr/lib/python3.10/site-packages/protonvpn_cli/cli_wrapper.py", line 73, in login
>     self.protonvpn.login(username, password)
>   File "/usr/lib/python3.10/site-packages/protonvpn_nm_lib/api.py", line 36, in login
>     self._env.api_session.authenticate(username, password, human_verification)
>   File "/usr/lib/python3.10/site-packages/protonvpn_nm_lib/core/session/session.py", line 48, in __call__
>     raise UnreacheableAPIError("Unable to reach API")
> protonvpn_nm_lib.exceptions.UnreacheableAPIError: Unable to reach API
> 2022-06-04 08:17:25,283 — cli.py — INFO — __init__:17 —

**Comment by aliazani** [comment]
> @calexandru2018 After long period of time, I've tested official version again but now I'm facing Network error with alternate routing enable like below:
> 
> > 2022-06-04 08:17:28,967 — cli.py — INFO — **init**:29 — Proton VPN CLI v3.12.0 (protonvpn-nm-lib v3.10.0; proton-client v0.7.1)
> > 2022-06-04 08:17:28,969 — cli.py — INFO — **init**:64 — CLI command: Namespace(command='login', version=False, help=False, get_logs=False)
> > 2022-06-04 08:17:33,671 — cli_wrapper.py — INFO — login:68 — Credentials provided, attempting to login
> > 2022-06-04 08:18:37,365 — cli_wrapper.py — ERROR — login:117 — Network error
> > Traceback (most recent call last):
> > File "/usr/lib/python3.10/site-packages/protonvpn_cli/cli_wrapper.py", line 73, in login
> > self.protonvpn.login(username, password)
> > File "/usr/lib/python3.10/site-packages/protonvpn_nm_lib/api.py", line 36, in login
> > self._env.api_session.authenticate(username, password, human_verification)
> > File "/usr/lib/python3.10/site-packages/protonvpn_nm_lib/core/session/session.py", line 39, in **call**
> > result = self._func(session, *args, **kwargs)
> > File "/usr/lib/python3.10/site-packages/protonvpn_nm_lib/core/session/session.py", line 390, in authenticate
> > self.__proton_api.authenticate(username, password)
> > File "/usr/lib/python3.10/site-packages/proton/api.py", line 387, in authenticate
> > info_response = self.api_request("/auth/info", payload)
> > File "/usr/lib/python3.10/site-packages/proton/api.py", line 261, in api_request
> > response = self.__try_with_alt_routing(fct, **request_params)
> > File "/usr/lib/python3.10/site-packages/proton/api.py", line 327, in __try_with_alt_routing
> > raise NetworkError("Network error")
> > proton.exceptions.NetworkError: Network error
> 
> And without alternate routing I face Unable to reach API like below:
> 
> > 2022-06-04 08:15:38,701 — cli.py — INFO — **init**:29 — Proton VPN CLI v3.12.0 (protonvpn-nm-lib v3.10.0; proton-client v0.7.1)
> > 2022-06-04 08:15:38,702 — cli.py — INFO — **init**:64 — CLI command: Namespace(command='login', version=False, help=False, get_logs=False)
> > 2022-06-04 08:15:39,798 — cli_wrapper.py — INFO — login:68 — Credentials provided, attempting to login
> > 2022-06-04 08:16:08,975 — cli_wrapper.py — ERROR — login:93 — Unable to reach API
> > Traceback (most recent call last):
> > File "/usr/lib/python3.10/site-packages/protonvpn_nm_lib/core/session/session.py", line 39, in **call**
> > result = self._func(session, *args, **kwargs)
> > File "/usr/lib/python3.10/site-packages/protonvpn_nm_lib/core/session/session.py", line 390, in authenticate
> > self.__proton_api.authenticate(username, password)
> > File "/usr/lib/python3.10/site-packages/proton/api.py", line 387, in authenticate
> > info_response = self.api_request("/auth/info", payload)
> > File "/usr/lib/python3.10/site-packages/proton/api.py", line 256, in api_request
> > raise exception_class(exception_msg)
> > proton.exceptions.NewConnectionError: TLSPinningHTTPSConnectionPool(host='api.protonvpn.ch', port=443): Max retries exceeded with url: /auth/info (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fc911e0ded0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))
> > During handling of the above exception, another exception occurred:
> > Traceback (most recent call last):
> > File "/usr/lib/python3.10/site-packages/protonvpn_cli/cli_wrapper.py", line 73, in login
> > self.protonvpn.login(username, password)
> > File "/usr/lib/python3.10/site-packages/protonvpn_nm_lib/api.py", line 36, in login
> > self._env.api_session.authenticate(username, password, human_verification)
> > File "/usr/lib/python3.10/site-packages/protonvpn_nm_lib/core/session/session.py", line 48, in **call**
> > raise UnreacheableAPIError("Unable to reach API")
> > protonvpn_nm_lib.exceptions.UnreacheableAPIError: Unable to reach API
> > 2022-06-04 08:17:25,283 — cli.py — INFO — **init**:17 —

I consider all related to reaching api becuase log file of proton-client.log is like below:

> 2022-06-04 08:24:26,280 — api.py — ERROR — api_request:246 — TLSPinningHTTPSConnectionPool(host='api.protonvpn.ch', port=443): Max retries exceeded with url: /auth/info (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f0b3507de70>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))
> Traceback (most recent call last):
>   File "/usr/lib/python3.10/site-packages/urllib3/connection.py", line 174, in _new_conn
>     conn = connection.create_connection(
>   File "/usr/lib/python3.10/site-packages/urllib3/util/connection.py", line 72, in create_connection
>     for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
>   File "/usr/lib/python3.10/socket.py", line 955, in getaddrinfo
>     for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
> socket.gaierror: [Errno -3] Temporary failure in name resolution
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/usr/lib/python3.10/site-packages/urllib3/connectionpool.py", line 703, in urlopen
>     httplib_response = self._make_request(
>   File "/usr/lib/python3.10/site-packages/urllib3/connectionpool.py", line 386, in _make_request
>     self._validate_conn(conn)
>   File "/usr/lib/python3.10/site-packages/proton/cert_pinning.py", line 90, in _validate_conn
>     super(TLSPinningHTTPSConnectionPool, self)._validate_conn(conn)
>   File "/usr/lib/python3.10/site-packages/urllib3/connectionpool.py", line 1040, in _validate_conn
>     conn.connect()
>   File "/usr/lib/python3.10/site-packages/urllib3/connection.py", line 358, in connect
>     self.sock = conn = self._new_conn()
>   File "/usr/lib/python3.10/site-packages/urllib3/connection.py", line 186, in _new_conn
>     raise NewConnectionError(
> urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x7f0b3507de70>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution

I'm wondering why can't change api.protonmail.ch to solve the problem!
