### ISSUE TITLE
connection issue

### ISSUE THREAD

**Issue by bozoi3** [ProtonVPN/linux-cli#100]
running version:
Proton VPN CLI v3.13.0 (protonvpn-nm-lib v3.14.0; proton-client v0.7.1)

when trying to connect to other country my routing table is trashed with pvpnroutintrf0 and 
Destination     Gateway         Genmask         Flags Metric Ref    Use Iface
0.0.0.0         0.0.0.0         128.0.0.0       U     97     0        0 pvpnroutintrf0

and this error and connection halted 

`During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/proton/api.py", line 240, in api_request
    response = self.__make_request(fct, **request_params)
  File "/usr/lib/python3/dist-packages/proton/api.py", line 339, in __make_request
    raise NewConnectionError(e)
proton.exceptions.NewConnectionError: TLSPinningHTTPSConnectionPool(host='api.protonvpn.ch', port=443): Max retries exceeded with url: /vpn/location (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fb1a79eb040>: Failed to establish a new connection: [Errno -2] Name or service not known'))
2023-03-28 18:39:51,735 — api.py — ERROR — api_request:246 — TLSPinningHTTPSConnectionPool(host='api.protonvpn.ch', port=443): Max retries exceeded with url: /vpn/location (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fb1a79eb040>: Failed to establish a new connection: [Errno -2] Name or service not known'))
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 169, in _new_conn
    conn = connection.create_connection(
  File "/usr/lib/python3/dist-packages/urllib3/util/connection.py", line 73, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "/usr/lib/python3.10/socket.py", line 955, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -2] Name or service not known
`

any idea
----------------------------------------

**Comment by MatthewLM** [comment]
I started to get what appears to be the same issue causing disconnections overnight:

```
2023-09-19 06:34:59,832 — api.py — ERROR — api_request:246 — TLSPinningHTTPSConnectionPool(host
='api.protonvpn.ch', port=443): Max retries exceeded with url: /vpn/logicals (Caused by NewConn
ectionError('<urllib3.connection.HTTPSConnection object at 0x7f4347f1fc90>: Failed to establish
 a new connection: [Errno -2] Name or service not known'))
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 174, in _new_conn
    conn = connection.create_connection(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/urllib3/util/connection.py", line 73, in create_connecti
on
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/socket.py", line 962, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
socket.gaierror: [Errno -2] Name or service not known

```
