### ISSUE TITLE
[BUG] Can't connect inside docker container

### ISSUE THREAD

**Issue by krey** [ProtonVPN/linux-cli#120]
**Describe the bug**
Docker doesn't let you rename `/etc/resolv.conf`

**To Reproduce**
Set up a Dockerfile
```
FROM archlinux

RUN pacman -Sy && \
    pacman -S --noconfirm which openvpn dialog python-pip python-setuptools && \
    pip install protonvpn-cli
```

**Expected behavior**
Should connect

**Error Messages/Program Output/Log Messages (~/.pvpn-cli/pvpn-cli.log)**
```
[root@5f15d9d2218c /]# protonvpn connect -f
Connecting to AT#5 via UDP...
Traceback (most recent call last):
  File "/usr/sbin/protonvpn", line 8, in <module>
    sys.exit(main())
  File "/usr/lib/python3.8/site-packages/protonvpn_cli/cli.py", line 73, in main
    cli()
  File "/usr/lib/python3.8/site-packages/protonvpn_cli/cli.py", line 116, in cli
    connection.fastest(protocol)
  File "/usr/lib/python3.8/site-packages/protonvpn_cli/connection.py", line 165, in fastest
    openvpn_connect(fastest_server, protocol)
  File "/usr/lib/python3.8/site-packages/protonvpn_cli/connection.py", line 501, in openvpn_connect
    manage_dns("leak_protection", dns_server)
  File "/usr/lib/python3.8/site-packages/protonvpn_cli/connection.py", line 587, in manage_dns
    for line in fileinput.input(resolvconf_path, inplace=True):
  File "/usr/lib/python3.8/fileinput.py", line 248, in __next__
    line = self._readline()
  File "/usr/lib/python3.8/fileinput.py", line 342, in _readline
    os.rename(self._filename, self._backupfilename)
OSError: [Errno 16] Device or resource busy: '/etc/resolv.conf' -> '/etc/resolv.conf.bak'
```

**Desktop (please complete the following information):**
 - OS: Arch Linux container inside Arch Linux
 - Python Version: 3.8.1
 - ProtonVPN-CLI Version: v2.2.2

**Comment by Rafficer** [comment]
Looks like something is using that file already, hence it can't be edited?

**Comment by krey** [comment]
@Rafficer I can edit it, but it's not happy with it being renamed. It's a backup operation fileinput does

**Comment by Rafficer** [comment]
Alright. Thanks for the PR, I'll take a look at it.

Tbh, I didn't know fileinput does that in the first place.
