### ISSUE TITLE
[Enhancement] Python 3.4 Support

### ISSUE THREAD

**Issue by sadsfae** [ProtonVPN/linux-cli#170]
Hi ProtonVPN team,

I am a plus subscriber that has a few systems where I cannot upgrade to Python 3.5+ (stuck on Python 3.4).  I know I can use direct openvpn in those cases but I'd live to use the `linux-cli` to continue to use ProtonVPN.

I get the following errors trying to initiate protonvpn after `pip3` installation per the docs which seems related to not being on Python 3.5+ as outlined as a requirement.

```
# protonvpn init
Traceback (most recent call last):
  File "/usr/bin/protonvpn", line 11, in <module>
    sys.exit(main())
  File "/usr/lib/python3.4/site-packages/protonvpn_cli/cli.py", line 73, in main
    cli()
  File "/usr/lib/python3.4/site-packages/protonvpn_cli/cli.py", line 83, in cli
    change_file_owner(os.path.join(CONFIG_DIR, "pvpn-cli.log"))
  File "/usr/lib/python3.4/site-packages/protonvpn_cli/utils.py", line 311, in change_file_owner
    stdout=subprocess.PIPE).stdout)
AttributeError: 'module' object has no attribute 'run'
```

Is there any way to get a fix here so it works on earlier versions of Python3?

**Comment by Rafficer** [comment]
No, sorry. 3.4 support won't happen.
