### ISSUE TITLE
Installing from source

### ISSUE THREAD

**Issue by Xashyar** [ProtonVPN/linux-cli#195]
**Describe the bug**
After installing from source, protonvpn fails to run.

**To Reproduce**

1.  Clone this repository

`git clone https://github.com/protonvpn/linux-cli`

2. Step into the directory

`cd linux-cli`

3. Install

`pip3 install -e .`

4. Run

`sudo protonvpn c`

<details>
 <summary> Error Messages/Program Output/Log Messages (~/.pvpn-cli/pvpn-cli.log)  </summary>

```
Traceback (most recent call last):
  File "/home/xashyar/.local/bin/protonvpn", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 3262, in <module>
    def _initialize_master_working_set():
  File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 3245, in _call_aside
    f(*args, **kwargs)
  File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 3274, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 584, in _build_master
    ws.require(__requires__)
  File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 901, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 787, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'protonvpn-cli' distribution was not found and is required by the application

```

</details>

**Desktop (please complete the following information):**
 - OS: Manjaro 20.03
 - Python Version: 3.8.3
 - ProtonVPN-CLI Version: 2.2.4

**Comment by Rafficer** [comment]
You've installed it in your local python namespace and then call it with root's namespace.

**Comment by Kaukov** [comment]
Yes, as Rafficer said - you installed it for the user namespace and not the root one. You need to execute `sudo pip3 install -e .` and it'll be fine

**Comment by Xashyar** [comment]
Thanks! @Rafficer @Kaukov

Should `README.md` be updated accordingly as well?

**Comment by Rafficer** [comment]
That's why it says that it should be installed in a virtual environment.
