### ISSUE TITLE
Pyhton Errors

### ISSUE THREAD

**Issue by palanthis** [ProtonVPN/linux-cli#198]
Worked fine this morning. Now throwing the below error. Arch Linux. Kernel 5.7.2, Python 3.8.3-1

Traceback (most recent call last):
  File "/usr/bin/protonvpn", line 9, in <module>
    for entry_point in distribution('protonvpn-cli==2.2.4').entry_points:
  File "/usr/lib/python3.8/importlib/metadata.py", line 504, in distribution
    return Distribution.from_name(distribution_name)
  File "/usr/lib/python3.8/importlib/metadata.py", line 177, in from_name
    raise PackageNotFoundError(name)

**Comment by palanthis** [comment]
Disregard - It was an issue with PySetup in the Arch repos and has been resolved. I did have to manually remove and reinstall ProtonVPN, as the remove function still called the script and threw the error.
