### ISSUE TITLE
i get this when trying to do anything with it

### ISSUE THREAD

**Issue by D0nnieD4rk0** [ProtonVPN/linux-cli#20]

**Comment by niva42** [comment]
Similar here:
Traceback (most recent call last):
  File "/usr/bin/protonvpn-cli", line 33, in <module>
    sys.exit(load_entry_point('protonvpn-cli==3.7.1', 'console_scripts', 'protonvpn-cli')())
  File "/usr/lib/python3.9/site-packages/protonvpn_cli/main.py", line 21, in main
    ProtonVPNCLI()
  File "/usr/lib/python3.9/site-packages/protonvpn_cli/cli.py", line 63, in __init__
    getattr(self, args.command)()
  File "/usr/lib/python3.9/site-packages/protonvpn_cli/cli.py", line 69, in c
    self.connect()
  File "/usr/lib/python3.9/site-packages/protonvpn_cli/cli.py", line 130, in connect
    self.cli_wrapper.connect(args)
  File "/usr/lib/python3.9/site-packages/protonvpn_cli/cli_wrapper.py", line 235, in connect
    self._connect()
  File "/usr/lib/python3.9/site-packages/protonvpn_cli/cli_wrapper.py", line 286, in _connect
    connect_response = self.protonvpn.connect()
  File "/usr/lib/python3.9/site-packages/protonvpn_nm_lib/api.py", line 47, in connect
    connect_result = self._env.connection_backend.connect()
  File "/usr/lib/python3.9/site-packages/protonvpn_nm_lib/core/connection_backend/nm_client/n
m_client.py", line 103, in connect
    dbus_loop.run()
  File "/usr/lib/python3.9/site-packages/gi/overrides/GLib.py", line 497, in run
    super(MainLoop, self).run()
  File "/usr/lib/python3.9/contextlib.py", line 124, in __exit__
    next(self.gen)
  File "/usr/lib/python3.9/site-packages/gi/_ossighelper.py", line 237, in register_sigint_fa
llback
    signal.default_int_handler(signal.SIGINT, None)
KeyboardInterrupt

**Comment by calexandru2018** [comment]
Hey @D0nnieD4rk0 

It would help if you would provide information on your distro. Is this on a Fedora system ?

**Comment by D0nnieD4rk0** [comment]
im on manjaro, installed the thing off the AUR

**Comment by D0nnieD4rk0** [comment]
so there anything i can do ?

**Comment by calexandru2018** [comment]
`StopIteration` usually happens when packages that create binaries were not correctly removed, which leads me to think that you haven't correctly (and fully) uninstalled the community client.

**Comment by Pavlina1979** [comment]
I had the same problem and calexandru2018 is right, previously I did not fully uninstalled the comunity version. Now the proton-cli works great again. Here is guide how to do it properly:
https://protonvpn.com/support/official-linux-client-arch/
just scroll down and under "Notes" there is how to do it.

**Comment by durierem** [comment]
I had the same issue. Thanks @Pavlina1979!

I think it's pretty common to improperly uninstall the old community version. Maybe it could be useful to point that out directly on the README?

**Comment by niva42** [comment]
Can't get it to work sadly. I had uninstalled the older community version (from the AUR on arch) already. But I did not do the 'Purge' thing described in https://protonvpn.com/support/official-linux-client-arch/ .
So I uninstalled the official linux client and reinstalled the older community version. I then did the Purge thing as described and uninstalled it again. 
I then reinstalled the official version again but nothing has changed. I still can't connect to any of the Proton VPN. 
When I try to connect with 
  protonvpn-cli c
it just stalls with after the output:
  Setting up ProtonVPN.
  Connecting to ProtonVPN on DE#12 with UDP.

**Comment by calexandru2018** [comment]
@niva42 your issue is not related to this ticket. Please take a look at this: https://github.com/ProtonVPN/linux-app/issues/9

**Comment by 23Yamahar6** [comment]
I have the same issue, I've tried reinstalling protonvpn-cli, I've installed protonvpn-gui (in case it would fix it) and nothing works.

I broke it after uninstalling it, I was having issues connecting to the VPNs, so I did "sudo pacman -R protonvpn-cli" and went ahead to delete all of the folders containing "protonvpn". 

This is the message I get after typing protonvpn-cli:

Traceback (most recent call last):
  File "/usr/bin/protonvpn-cli", line 33, in <module>
    sys.exit(load_entry_point('protonvpn-cli==3.8.0', 'console_scripts', 'protonvpn-cli')())
  File "/usr/lib/python3.9/site-packages/protonvpn_cli/main.py", line 20, in main
    from .cli import ProtonVPNCLI
  File "/usr/lib/python3.9/site-packages/protonvpn_cli/cli.py", line 5, in <module>
    from protonvpn_nm_lib.constants import APP_VERSION as lib_version
ModuleNotFoundError: No module named 'protonvpn_nm_lib.constants'

The landlord has a lot of content blocked in their wifi and I can't even access the official protonvpn website.

Any ideas on how to fix it?

Thanks in advance.

**Comment by rexmightlag** [comment]
I have the issue as @D0nnieD4rk0, at least when I run it without any elevated privileges. It works fine when I run as root (sudo)

**Comment by rexmightlag** [comment]
> I have the issue as @D0nnieD4rk0, at least when I run it without any elevated privileges. It works fine when I run as root (sudo)

Welp, a second after writing this, I figured out what was causing the problem. The old python packages from the dir .local/lib/python were causing a conflict with the packages that the new protonvpn cli version had installed (I was using the community version before).

I just deleted all the python related packages from .local/lib/ and the protonvpn-cli started working. If you  have other python related stuff in the local lib directory, you might need to find and remove the conflicting packages one by one. In my case I had nothing important there, so I deleted the whole python3.9 directory.

**Comment by calexandru2018** [comment]
@rexmightlag your emot supposed to run the official client with sudo.

**Comment by rexmightlag** [comment]
> @rexmightlag you're not supposed to run the official client with sudo.

hello, yes I know that, that is why I was wondering why it was not working without sudo. That is why I thought of deleting the local python files in the '.local/lib/ folder'. After I did that, it worked without sudo.

> > I have the issue as @D0nnieD4rk0, at least when I run it without any elevated privileges. It works fine when I run as root (sudo)
> 
> Welp, a second after writing this, I figured out what was causing the problem. The old python packages from the dir .local/lib/python were causing a conflict with the packages that the new protonvpn cli version had installed (I was using the community version before).
> 
> I just deleted all the python related packages from .local/lib/ and the protonvpn-cli started working. If you have other python related stuff in the local lib directory, you might need to find and remove the conflicting packages one by one. In my case I had nothing important there, so I deleted the whole python3.9 directory.

**Comment by klownie** [comment]
Yea i have the same issue on arch.
I installed proton-cli via the AUR with paru and it does not work with the same message.
I also tried deleting everythin with `paru -Rcsn protonvpn-cli` and it still does no work after reintall.

**Comment by GabrielRavier** [comment]
Can confirm I also get similar issues which I solved by removing the `python3-qpid-proton` package from my Fedora installation.
