### ISSUE TITLE
[BUG] .pvpn-cli dir does not exist or can't be found

### ISSUE THREAD

**Issue by misterbit-pro** [ProtonVPN/linux-cli#209]
**Describe the bug**
.pvpn-cli dir does not exist or can't be found

**To Reproduce**
1. type protonvpn in shell

**Expected behavior**
Give ne options to do something and do not throw a error

**Error Messages/Program Output/Log Messages (~/.pvpn-cli/pvpn-cli.log)**
root@787e75b87ad9:/setup/linux-cli# protonvpn
Traceback (most recent call last):
  File "/usr/local/bin/protonvpn", line 11, in <module>
    load_entry_point('protonvpn-cli', 'console_scripts', 'protonvpn')()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 489, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2793, in load_entry_point
    return ep.load()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2411, in load
    return self.resolve()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2417, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/setup/linux-cli/protonvpn_cli/cli.py", line 11, in <module>
    from . import connection
  File "/setup/linux-cli/protonvpn_cli/connection.py", line 15, in <module>
    from .logger import logger
  File "/setup/linux-cli/protonvpn_cli/logger.py", line 40, in <module>
    logger = get_logger()
  File "/setup/linux-cli/protonvpn_cli/logger.py", line 20, in get_logger
    os.mkdir(CONFIG_DIR)
FileNotFoundError: [Errno 2] No such file or directory: '~JTQ76VcHFe7FZ2m-0epJkMe4/.pvpn-cli'

**Desktop (please complete the following information):**
 - OS: Debian stable docker
 - Python Version: Python 3.7.3
 - ProtonVPN-CLI Version: latest

**Additional context**
Running it in a docker container

**Comment by Rafficer** [comment]
> ~JTQ76VcHFe7FZ2m-0epJkMe4/.pvpn-cli

Your username should be root, not that string. Check your environment variables.

**Comment by misterbit-pro** [comment]
Oh i see, thanks.
