### ISSUE TITLE
[BUG]KeyError: 'resolvconf_hash'

### ISSUE THREAD

**Issue by longwuyuan** [ProtonVPN/linux-cli#210]
**Describe the bug**
Connection attempt results in KeyErr: 'resolvconf_hash'
**To Reproduce**
1. Install protonvpn on ubuntu lts as per docs
2. IPv6 is disabled in kernel
3. Configure protonpn
4. Try to connect to random server

**Expected behavior**
Protonpn should connect

**Error Messages/Program Output/Log Messages (~/.pvpn-cli/pvpn-cli.log)**
sudo protonvpn c -r                                                                            130 _
Traceback (most recent call last):
  File "/usr/local/bin/protonvpn", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.8/dist-packages/protonvpn_cli/cli.py", line 73, in main
    cli()
  File "/usr/local/lib/python3.8/dist-packages/protonvpn_cli/cli.py", line 114, in cli
    connection.random_c(protocol)
  File "/usr/local/lib/python3.8/dist-packages/protonvpn_cli/connection.py", line 139, in random_c
    openvpn_connect(servername, protocol)
  File "/usr/local/lib/python3.8/dist-packages/protonvpn_cli/connection.py", line 456, in openvpn_connect
    disconnect(passed=True)
  File "/usr/local/lib/python3.8/dist-packages/protonvpn_cli/connection.py", line 344, in disconnect
    manage_dns("restore")
  File "/usr/local/lib/python3.8/dist-packages/protonvpn_cli/connection.py", line 610, in manage_dns
    oldhash = get_config_value("metadata", "resolvconf_hash")
  File "/usr/local/lib/python3.8/dist-packages/protonvpn_cli/utils.py", line 123, in get_config_value
    return config[group][key]
  File "/usr/lib/python3.8/configparser.py", line 1254, in __getitem__
    raise KeyError(key)
KeyError: 'resolvconf_hash'

**Desktop (please complete the following information):**
 - OS: Ubuntu 20 LTS
 - Python Version: 3.8.2
 - ProtonVPN-CLI Version: 2.2.4 

**Additional context**

**Comment by longwuyuan** [comment]
What other info would be helpul to add here

**Comment by longwuyuan** [comment]
just to delete $HOME/.resol*

**Comment by fbmnds** [comment]
There is still a cornercase where no previous hash file was generated.
I fixed it with:

    ```
           # /usr/local/lib/python3.6/dist-packages/protonvpn_cli/connection.py, around line 612 
            
            # Check if the file changed since connection
            try:
                oldhash = get_config_value("metadata", "resolvconf_hash")
            except:
                oldhash = 0
            with open(resolvconf_path, "rb") as f:
                filehash = zlib.crc32(f.read())
    ```

**Comment by joker7sahebi** [comment]
https://github.com/ProtonVPN/linux-cli-community/issues/263#issuecomment-749235217
