### ISSUE TITLE
protonvpn-cli 2.2.4 does not execute-  AttributeError: 'module' has no attribute 'run'

### ISSUE THREAD

**Issue by ishmartbuoy** [ProtonVPN/linux-cli#213]
**Bug Description**
protonvpn does not execute

**Triggering the error**
Executing `sudo protonvpn` throws the below error 
 
Traceback (most recent call last):  File "/usr/local/bin/protonvpn", line 9, in <module>  load_entry_point('protonvpn-cli==2.2.4', 'console_scripts', 'protonvpn')()
 File "/opt/linux-cli/protonvpn_cli/cli.py", line 27, in main  cli() 
 File "/opt/linux-cli/protonvpn_cli/cli.py", line 37, in cli change_file_owner(os.path.join(CONFIG_DIR, "pvpn-cli.log"))
File "/opt/linux-cli/protonvpn_cli/utils.py", line 313, in change_file_owner uid = int(subprocess.run(["id", "-u", USER],AttributeError: 'module' object has no attribute 'run'

**System Information:**
 - OS: Linux Mint 17.3
 - Python Version: 3.4.4 
 - ProtonVPN-CLI Version: 2.2.4

**Comment by Rafficer** [comment]
Python 3.4 is not supported.

You should upgrade your distro. Linux Mint 17 is EOL and not receiving any security patches anymore.
