### ISSUE TITLE
[BUG] Unable to start after installing. Prints python traceback.

### ISSUE THREAD

**Issue by BennyRoesler** [ProtonVPN/linux-cli#225]
**Describe the bug**
Trying to run `sudo protonvpn c --p2p` prints a python traceback. This is after a fresh OS install and following the install instructions for protonvpn and dependencies

**To Reproduce**
1. Install protonvpn and dependencies (followed instructions on README)
2. Run protonvpn - `sudo protonvpn c` 

**Expected behavior**
Normally I would be prompted to initialize protonvpn or it will connect on its own.

**Error Messages/Program Output/Log Messages (~/.pvpn-cli/pvpn-cli.log)**
`~/.pvpn-cli/pvpn-cli.log:` Does not contain data

Output from `sudo protonvpn c`:

```
Traceback (most recent call last):
  File "/home/roeslerb/.local/bin/protonvpn", line 5, in <module>
    from protonvpn_cli.cli import main
  File "/usr/lib/python3.8/site-packages/protonvpn_cli/cli.py", line 57, in <module>
    from . import connection
  File "/usr/lib/python3.8/site-packages/protonvpn_cli/connection.py", line 16, in <module>
    from .utils import (
  File "/usr/lib/python3.8/site-packages/protonvpn_cli/utils.py", line 14, in <module>
    from jinja2 import Environment, FileSystemLoader
  File "/usr/lib/python3.8/site-packages/jinja2/__init__.py", line 6, in <module>
    from markupsafe import escape
ImportError: cannot import name 'escape' from 'markupsafe' (unknown location)

```

**Desktop (please complete the following information):**
 - OS: Manjaro 20.0.3
 - Python Version: Python 3.8.5
 - ProtonVPN-CLI Version: Unknown.`protonvpn --version` prints the same error above. I believe it is the latest version.

**Additional context**
1.This is after a fresh install of Manjaro 20.0.3 KDE
2.I uninstalled `protonvpn-cli` after each failed attempt.

**Behavior installing protonvpn with pip**
1. Installs correctly
2. `sudo protonvpn c` prints this error
```
Traceback (most recent call last):
  File "/home/[user]/.local/bin/protonvpn", line 5, in <module>
    from protonvpn_cli.cli import main
ModuleNotFoundError: No module named 'protonvpn_cli'
```
3. `protonvpn c' prints the error in the program output section

**Behavior installing protonvpn with pip3**
Same behavior as installing with pip

**Comment by samqld** [comment]
Can confirm. having the same issue on OS:Arch Linux x86_64 Kernel: 5.9.8-arch1-1

**Comment by unbranched** [comment]
Update via pip as described here:
https://github.com/ProtonVPN/linux-cli/blob/master/USAGE.md#updating-protonvpn-cli

**Comment by samqld** [comment]
> Update via pip as described here:
> https://github.com/ProtonVPN/linux-cli/blob/master/USAGE.md#updating-protonvpn-cli

This resolved the issue for me
