### ISSUE TITLE
pls help me.

### ISSUE THREAD

**Issue by phanthuthao** [ProtonVPN/linux-cli#262]
sudo protonvpn init
Traceback (most recent call last):
  File "/usr/local/bin/protonvpn", line 5, in <module>
    from protonvpn_cli.cli import main
  File "/usr/local/lib/python3.9/dist-packages/protonvpn_cli/cli.py", line 57, in <module>
    from . import connection
  File "/usr/local/lib/python3.9/dist-packages/protonvpn_cli/connection.py", line 16, in <module>
    from .utils import (
  File "/usr/local/lib/python3.9/dist-packages/protonvpn_cli/utils.py", line 13, in <module>
    import requests
  File "/usr/lib/python3/dist-packages/requests/__init__.py", line 120, in <module>
    from . import utils
  File "/usr/lib/python3/dist-packages/requests/utils.py", line 25, in <module>
    from . import certs
  File "/usr/lib/python3/dist-packages/requests/certs.py", line 15, in <module>
    from certifi import where
ModuleNotFoundError: No module named 'certifi'

**Comment by ErichRitz** [comment]
I believe you need the certifi python3 module: https://pypi.org/project/certifi/

Either install it using your normal system installation procedure, or use pip as described on the webpage.

**Comment by phanthuthao** [comment]
> I believe you need the certifi python3 module: https://pypi.org/project/certifi/
> 
> Either install it using your normal system installation procedure, or use pip as described on the webpage.

Thanks so much.
