### ISSUE TITLE
[BUG] Unable to connect after updating to 2.2.6

### ISSUE THREAD

**Issue by umbertix** [ProtonVPN/linux-cli#263]
**Describe the bug**
Error raised right after having upgraded to the latest version.

**To Reproduce**
```
pi@mediaserver:~ $ sudo protonvpn c -f
Traceback (most recent call last):
  File "/usr/local/bin/protonvpn", line 10, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.7/dist-packages/protonvpn_cli/cli.py", line 73, in main
    cli()
  File "/usr/local/lib/python3.7/dist-packages/protonvpn_cli/cli.py", line 116, in cli
    connection.fastest(protocol)
  File "/usr/local/lib/python3.7/dist-packages/protonvpn_cli/connection.py", line 150, in fastest
    disconnect(passed=True)
  File "/usr/local/lib/python3.7/dist-packages/protonvpn_cli/connection.py", line 344, in disconnect
    manage_dns("restore")
  File "/usr/local/lib/python3.7/dist-packages/protonvpn_cli/connection.py", line 612, in manage_dns
    oldhash = get_config_value("metadata", "resolvconf_hash")
  File "/usr/local/lib/python3.7/dist-packages/protonvpn_cli/utils.py", line 123, in get_config_value
    return config[group][key]
  File "/usr/lib/python3.7/configparser.py", line 1251, in __getitem__
    raise KeyError(key)
KeyError: 'resolvconf_hash'

```

I have tried from resintalling, to resetting the config, checking if there is anything to upgrade in the system or the packages but so far I can't really see anything. I would gladly provide any more details on the system.

Much appreciated.

**Comment by shariqsami** [comment]
Facing the same issue here
`Traceback (most recent call last):
  File "/usr/local/bin/protonvpn", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.5/dist-packages/protonvpn_cli/cli.py", line 73, in main
    cli()
  File "/usr/local/lib/python3.5/dist-packages/protonvpn_cli/cli.py", line 129, in cli
    connection.dialog()
  File "/usr/local/lib/python3.5/dist-packages/protonvpn_cli/connection.py", line 124, in dialog
    openvpn_connect(server_result, protocol_result)
  File "/usr/local/lib/python3.5/dist-packages/protonvpn_cli/connection.py", line 456, in openvpn_connect
    disconnect(passed=True)
  File "/usr/local/lib/python3.5/dist-packages/protonvpn_cli/connection.py", line 344, in disconnect
    manage_dns("restore")
  File "/usr/local/lib/python3.5/dist-packages/protonvpn_cli/connection.py", line 610, in manage_dns
    oldhash = get_config_value("metadata", "resolvconf_hash")
  File "/usr/local/lib/python3.5/dist-packages/protonvpn_cli/utils.py", line 123, in get_config_value
    return config[group][key]
  File "/usr/lib/python3.5/configparser.py", line 1230, in __getitem__
    raise KeyError(key)
KeyError: 'resolvconf_hash'
`

**Comment by necromuralist** [comment]
I had the same problem just now so I followed the advice referenced in #62 and deleted the backup files.

```
rm ~/.pvpn-cli/*backup
```
And that fixed it for me.

**Comment by EdwardJennerZA** [comment]
I have had this same issue with several python packages over the last 24 hours. A full system upgrade resolved most of them but broke ProtonVPN CLI client.

Best I can tell something changed with the `metadata` package between python versions as it is the common element in all stack trace errors.

```
Traceback (most recent call last):
  File "/usr/bin/protonvpn", line 33, in <module>
    sys.exit(load_entry_point('protonvpn-cli==2.2.6', 'console_scripts', 'protonvpn')())
  File "/usr/bin/protonvpn", line 22, in importlib_load_entry_point
    for entry_point in distribution(dist_name).entry_points
  File "/usr/lib/python3.9/importlib/metadata.py", line 524, in distribution
    return Distribution.from_name(distribution_name)
  File "/usr/lib/python3.9/importlib/metadata.py", line 187, in from_name
    raise PackageNotFoundError(name)
importlib.metadata.PackageNotFoundError: protonvpn-cli
```

**Comment by umbertix** [comment]
Cleaning the backups as @necromuralist has suggested fixed it for me. I will close this issue for the time being Thx
