### ISSUE TITLE
[BUG] Startup issue on debian (python deps)

### ISSUE THREAD

**Issue by esavier** [ProtonVPN/linux-cli#272]
I can not properly install and use protonvpn-cli on debian (via apt)

```
[20:21:55][mia][09EBFB][L:1] ✔ esavier:/home/esavier:protonvpn-cli 
Traceback (most recent call last):
  File "/usr/bin/protonvpn-cli", line 11, in <module>
    load_entry_point('protonvpn-cli==3.1.0', 'console_scripts', 'protonvpn-cli')()
  File "/usr/lib/python3/dist-packages/protonvpn_cli/main.py", line 20, in main
    from .cli import ProtonVPNCLI
  File "/usr/lib/python3/dist-packages/protonvpn_cli/cli.py", line 9, in <module>
    from .cli_wrapper import CLIWrapper
  File "/usr/lib/python3/dist-packages/protonvpn_cli/cli_wrapper.py", line 32, in <module>
    from protonvpn_nm_lib.services.user_manager import UserManager
  File "/usr/lib/python3/dist-packages/protonvpn_nm_lib/services/user_manager.py", line 10, in <module>
    from .user_session_manager import UserSessionManager
  File "/usr/lib/python3/dist-packages/protonvpn_nm_lib/services/user_session_manager.py", line 14, in <module>
    class UserSessionManager:
  File "/usr/lib/python3/dist-packages/protonvpn_nm_lib/services/user_session_manager.py", line 16, in UserSessionManager
    keyring.backends.kwallet.DBusKeyring,
AttributeError: module 'keyring.backends' has no attribute 'kwallet'
```
System info:
```
No LSB modules are available.
Distributor ID:	Debian
Description:	Debian GNU/Linux bullseye/sid
Release:	testing
Codename:	bullseye
-------
Python 3.9.1

```

**Desktop (please complete the following information):**
 - OS: [e.g. Ubuntu 18.04]
 - Python Version: [e.g. 3.7.4 (`python3 --version`)]
 - ProtonVPN-CLI Version: [e.g. 2.0.0 (`protonvpn --version`)]

**Comment by gmillerd** [comment]
Issue 266?

**Comment by esavier** [comment]
yup, didn't see that one, closing as duplicate
