### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by perfecto25** [ProtonVPN/linux-cli#273]
**Describe the bug**

installed protonvpn cli on Linux Mint 20 (XFCE)

when running protonvpn-cli login 

getting this

```
Traceback (most recent call last):
  File "/usr/bin/protonvpn-cli", line 11, in <module>
    load_entry_point('protonvpn-cli==3.1.0', 'console_scripts', 'protonvpn-cli')()
  File "/usr/lib/python3/dist-packages/protonvpn_cli/main.py", line 21, in main
    ProtonVPNCLI()
  File "/usr/lib/python3/dist-packages/protonvpn_cli/cli.py", line 45, in __init__
    self.cli_wrapper = CLIWrapper()
  File "/usr/lib/python3/dist-packages/protonvpn_cli/cli_wrapper.py", line 67, in __init__
    self.ks_manager = KillSwitchManager(self.user_conf_manager)
  File "/usr/lib/python3/dist-packages/protonvpn_nm_lib/services/killswitch_manager.py", line 54, in __init__
    self.connectivity_check()
  File "/usr/lib/python3/dist-packages/protonvpn_nm_lib/services/killswitch_manager.py", line 353, in connectivity_check
    self.disable_connectivity_check(
  File "/usr/lib/python3/dist-packages/protonvpn_nm_lib/services/killswitch_manager.py", line 393, in disable_connectivity_check
    raise exceptions.DisableConnectivityCheckError(
protonvpn_nm_lib.exceptions.DisableConnectivityCheckError: Can not disable connectivity check for killswitch
Error in sys.excepthook:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/apport_python_hook.py", line 153, in apport_excepthook
    with os.fdopen(os.open(pr_filename,
FileNotFoundError: [Errno 2] No such file or directory: '/var/crash/_usr_bin_protonvpn-cli.1000.crash'

Original exception was:
Traceback (most recent call last):
  File "/usr/bin/protonvpn-cli", line 11, in <module>
    load_entry_point('protonvpn-cli==3.1.0', 'console_scripts', 'protonvpn-cli')()
  File "/usr/lib/python3/dist-packages/protonvpn_cli/main.py", line 21, in main
    ProtonVPNCLI()
  File "/usr/lib/python3/dist-packages/protonvpn_cli/cli.py", line 45, in __init__
    self.cli_wrapper = CLIWrapper()
  File "/usr/lib/python3/dist-packages/protonvpn_cli/cli_wrapper.py", line 67, in __init__
    self.ks_manager = KillSwitchManager(self.user_conf_manager)
  File "/usr/lib/python3/dist-packages/protonvpn_nm_lib/services/killswitch_manager.py", line 54, in __init__
    self.connectivity_check()
  File "/usr/lib/python3/dist-packages/protonvpn_nm_lib/services/killswitch_manager.py", line 353, in connectivity_check
    self.disable_connectivity_check(
  File "/usr/lib/python3/dist-packages/protonvpn_nm_lib/services/killswitch_manager.py", line 393, in disable_connectivity_check
    raise exceptions.DisableConnectivityCheckError(
protonvpn_nm_lib.exceptions.DisableConnectivityCheckError: Can not disable connectivity check for killswitch

```

**To Reproduce**
1. run protonvpn-cli login
2.

**Expected behavior**
login is accepted

**Error Messages/Program Output/Log Messages (~/.pvpn-cli/pvpn-cli.log)**
```
 cat /etc/lsb-release 
DISTRIB_ID=LinuxMint
DISTRIB_RELEASE=20.1
DISTRIB_CODENAME=ulyssa
DISTRIB_DESCRIPTION="Linux Mint 20.1 Ulyssa"

Linux mint20 5.4.0-58-generic #64-Ubuntu SMP Wed Dec 9 08:16:25 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

python3 --version
Python 3.8.5

protonvpn-cli --version
ProtonVPN CLI v3.1.0 (protonvpn-nm-lib v0.2.0; proton-client v0.1.0)


```

**Additional context**

**Comment by wellactuallyio** [comment]
Same issues, however, getting on `protonvpn-cli connect` with IPV6 Leak Protection
`Adding ProtonVPN connection...
Traceback (most recent call last):
  File "/usr/bin/protonvpn-cli", line 11, in <module>
    load_entry_point('protonvpn-cli==3.2.0', 'console_scripts', 'protonvpn-cli')()
  File "/usr/lib/python3/dist-packages/protonvpn_cli/main.py", line 21, in main
    ProtonVPNCLI()
  File "/usr/lib/python3/dist-packages/protonvpn_cli/cli.py", line 46, in __init__
    getattr(self, args.command)()
  File "/usr/lib/python3/dist-packages/protonvpn_cli/cli.py", line 111, in connect
    self.cli_wrapper.connect(args)
  File "/usr/lib/python3/dist-packages/protonvpn_cli/cli_wrapper.py", line 123, in connect
    conn_status = self.setup_connection(protocol)
  File "/usr/lib/python3/dist-packages/protonvpn_cli/cli_wrapper.py", line 546, in setup_connection
    self.add_vpn_connection(
  File "/usr/lib/python3/dist-packages/protonvpn_cli/cli_wrapper.py", line 651, in add_vpn_connection
    self.connection_manager.add_connection(
  File "/usr/lib/python3/dist-packages/protonvpn_nm_lib/services/connection_manager.py", line 115, in add_connection
    ipv6_lp_manager.manage("enable")
  File "/usr/lib/python3/dist-packages/protonvpn_nm_lib/services/ipv6_leak_protection_manager.py", line 49, in manage
    self.add_leak_protection()
  File "/usr/lib/python3/dist-packages/protonvpn_nm_lib/services/ipv6_leak_protection_manager.py", line 73, in add_leak_protection
    self.run_subprocess(
  File "/usr/lib/python3/dist-packages/protonvpn_nm_lib/services/ipv6_leak_protection_manager.py", line 121, in run_subprocess
    raise exception(exception_msg)
protonvpn_nm_lib.exceptions.EnableIPv6LeakProtectionError: Unable to add IPv6 leak protection connection/interface
Error in sys.excepthook:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/apport_python_hook.py", line 153, in apport_excepthook
    with os.fdopen(os.open(pr_filename,
FileNotFoundError: [Errno 2] No such file or directory: '/var/crash/_usr_bin_protonvpn-cli.1000.crash'

Original exception was:
Traceback (most recent call last):
  File "/usr/bin/protonvpn-cli", line 11, in <module>
    load_entry_point('protonvpn-cli==3.2.0', 'console_scripts', 'protonvpn-cli')()
  File "/usr/lib/python3/dist-packages/protonvpn_cli/main.py", line 21, in main
    ProtonVPNCLI()
  File "/usr/lib/python3/dist-packages/protonvpn_cli/cli.py", line 46, in __init__
    getattr(self, args.command)()
  File "/usr/lib/python3/dist-packages/protonvpn_cli/cli.py", line 111, in connect
    self.cli_wrapper.connect(args)
  File "/usr/lib/python3/dist-packages/protonvpn_cli/cli_wrapper.py", line 123, in connect
    conn_status = self.setup_connection(protocol)
  File "/usr/lib/python3/dist-packages/protonvpn_cli/cli_wrapper.py", line 546, in setup_connection
    self.add_vpn_connection(
  File "/usr/lib/python3/dist-packages/protonvpn_cli/cli_wrapper.py", line 651, in add_vpn_connection
    self.connection_manager.add_connection(
  File "/usr/lib/python3/dist-packages/protonvpn_nm_lib/services/connection_manager.py", line 115, in add_connection
    ipv6_lp_manager.manage("enable")
  File "/usr/lib/python3/dist-packages/protonvpn_nm_lib/services/ipv6_leak_protection_manager.py", line 49, in manage
    self.add_leak_protection()
  File "/usr/lib/python3/dist-packages/protonvpn_nm_lib/services/ipv6_leak_protection_manager.py", line 73, in add_leak_protection
    self.run_subprocess(
  File "/usr/lib/python3/dist-packages/protonvpn_nm_lib/services/ipv6_leak_protection_manager.py", line 121, in run_subprocess
    raise exception(exception_msg)
protonvpn_nm_lib.exceptions.EnableIPv6LeakProtectionError: Unable to add IPv6 leak protection connection/interface`

 I've tried disabling IPV6 via [https://protonvpn.com/support/disable-ipv6-protocol-linux/](url) with no luck.

**Comment by calexandru2018** [comment]
Hey @wellactuallyio 

This github repo is meant for the community built CLI and not the official one. Please contact support and close this issue.

**Comment by doomedraven** [comment]
i have fixed that adding print of args in 
`/usr/lib/python3/dist-packages/protonvpn_nm_lib/services/ipv6_leak_protection_manager.py`
that will show you something like:

`nmcli c a type dummy ifname ipv6leakintrf0 con-name pvpn-ipv6leak-protection ipv6.method manual ipv6.addresses X::/64 ipv6.gateway X::1 ipv6.route-metric 95`

so just run that as root and thats all

**Comment by DiagonalArg** [comment]
@doomedraven - I think you didn't mean to have X before ::/64 and ::1

Despite trying your approach, I now get the opposite error:

> $ protonvpn-cli c --cc CA -p udp
> Setting up ProtonVPN.

> Unable to remove IPv6 leak protection connection/interface

**Comment by doomedraven** [comment]
X is ipaddress

**Comment by DiagonalArg** [comment]
@doomedraven 
> X is ipaddress, from print

Don't know any python.  Can you tell me how to add "print of args"?

**Comment by doomedraven** [comment]
i don't see anymore those files in this repo

**Comment by DiagonalArg** [comment]
@doomedrave - it's there, just in a different location.

**Comment by calexandru2018** [comment]
Hey guys
@doomedraven when handling with NM and nmcli, sudo is not advised to use as NM is already configured for being used in non-sudo.

Also, usually the 
Unable to remove "IPv6 leak protection connection/interface" is because the system is not allowing the library to "manipulate" NM via dbus. This usually happens when there is a specific configuration on the system. Which one, that I haven't discovered yet, but you you look at NM logs you'll see that it says that the client does not have sufficient privileges, and thus is denied to add/remove the interface.

**Comment by doomedraven** [comment]
thanks @calexandru2018, finally installed it via pip and didn't had this problem, so that was from my tests to get it work
