### ISSUE TITLE
[BUG]linux cli 'value error'

### ISSUE THREAD

**Issue by vexusia** [ProtonVPN/linux-cli#287]
**Describe the bug**
Upon trying to connect using c or c -f on linux cli an error occurs. Unable to connect to a server. Other functionality still works.

**To Reproduce**
In terminal: protonvpn-cli c -f    
Using the regular selected server through c gives same issue.

**Expected behavior**
Expected to connect to fastest server or a selected server through c method

**Error Messages/Program Output/Log Messages (~/.pvpn-cli/pvpn-cli.log)**
Output:
Traceback (most recent call last):
  File "/usr/bin/protonvpn-cli", line 11, in <module>
    load_entry_point('protonvpn-cli==3.3.0', 'console_scripts', 'protonvpn-cli')()
  File "/usr/lib/python3/dist-packages/protonvpn_cli/main.py", line 21, in main
    ProtonVPNCLI()
  File "/usr/lib/python3/dist-packages/protonvpn_cli/cli.py", line 46, in __init__
    getattr(self, args.command)()
  File "/usr/lib/python3/dist-packages/protonvpn_cli/cli.py", line 50, in c
    self.connect()
  File "/usr/lib/python3/dist-packages/protonvpn_cli/cli.py", line 111, in connect
    self.cli_wrapper.connect(args)
  File "/usr/lib/python3/dist-packages/protonvpn_cli/cli_wrapper.py", line 124, in connect
    conn_status = self.setup_connection()
  File "/usr/lib/python3/dist-packages/protonvpn_cli/cli_wrapper.py", line 505, in setup_connection
    (
ValueError: too many values to unpack (expected 4)

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04.2 LTS
 - Python Version: Python 3.8.5
 - ProtonVPN-CLI Version: ProtonVPN CLI v3.3.0 (protonvpn-nm-lib v0.4.1; proton-client v0.3.0)

**Additional context**
Bug occurred after doing a system apt-get upgrade earlier today. Not sure if related to python update or packages of the cli wrapper.

**Comment by vexusia** [comment]
So I did another update and it pulled another update from the repo bringing nm-lib to v0.4.2. Not sure why this wasent pulled before unless it just got pushed but it seems to be working now as it should have been

Current version: 
ProtonVPN CLI v3.3.1 (protonvpn-nm-lib v0.4.2; proton-client v0.3.0)
