### ISSUE TITLE
Unable to connect after upgrade to 3.7.2

### ISSUE THREAD

**Issue by t3rmix** [ProtonVPN/linux-cli#29]
Hi,
after i upgraded to version 3.7.2, im unable to login or get logs from cli app (everything was fine until the upgrade). When i tried to use GUI app, the app just opens and keep spinning the waiting logo.

`$ protonvpn-cli c -r
Setting up ProtonVPN.

An unknown error has occured. Please ensure that you have internet connectivity.
If the issue persists, please contact support.`

$ protonvpn-cli --get-logs

Generating logs...
`
and there is no output from logs.

System info
Linux Mint 20.1 with 5.10.0-1034-oem
`$ protonvpn-cli -v

ProtonVPN CLI v3.7.2 (protonvpn-nm-lib v3.3.2; proton-client v0.5.1)
`
Any idea how to debug?

**Comment by calexandru2018** [comment]
Hey @t3rmix 

Could you try the following:
- `protonvpn-cli ks --off`
-` protonvpn-cli c -f`

**Comment by t3rmix** [comment]
@calexandru2018 thanks, but it doesn't help
```
$ protonvpn-cli ks --off

Kill switch has been disabled.

$ protonvpn-cli c -f
Setting up ProtonVPN.

An unknown error has occured. Please ensure that you have internet connectivity.
If the issue persists, please contact support.
```

**Comment by calexandru2018** [comment]
To get logs use ```protonvpn-cli --get-logs```

**Comment by t3rmix** [comment]
@calexandru2018 thanks, it takes around 5 minutes after running `protonvpn-cli --get-logs` to open file manager with logs :man_shrugging: 

The only thing i found is in protonvpn-cli.log

```
2021-07-08 10:19:19,934 — cli.py — INFO — __init__:17 — 
-------------------------------------------------

-----------	Initialized protonvpn-cli	-----------

-------------------------------------------------
2021-07-08 10:19:19,934 — cli.py — INFO — __init__:29 — ProtonVPN CLI v3.7.2 (protonvpn-nm-lib v3.3.2; proton-client v0.5.1)
2021-07-08 10:19:19,936 — cli.py — INFO — __init__:62 — CLI command: Namespace(command='c', get_logs=False, help=False, version=False)
2021-07-08 10:19:19,936 — cli.py — INFO — connect:126 — Options: Namespace(cc=None, fastest=False, help=False, p2p=False, protocol=None, random=True, sc=False, servername=None, tor=False)
2021-07-08 10:19:20,090 — cli_wrapper.py — ERROR — connect:227 — Expecting value: line 1 column 1 (char 0)
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/protonvpn_cli/cli_wrapper.py", line 147, in connect
    self.protonvpn.setup_connection(
  File "/usr/lib/python3/dist-packages/protonvpn_nm_lib/api.py", line 112, in setup_connection
    server = connect_configurations[connection_type](
  File "/usr/lib/python3/dist-packages/protonvpn_nm_lib/api.py", line 264, in config_for_random_server
    return self._env.api_session.servers.get_random_server()
  File "/usr/lib/python3/dist-packages/protonvpn_nm_lib/core/session/session.py", line 480, in servers
    self.__vpn_logicals.json_loads(f.read())
  File "/usr/lib/python3/dist-packages/protonvpn_nm_lib/core/servers/list.py", line 245, in json_loads
    self.__data = json.loads(data)
  File "/usr/lib/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.8/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```
Is there some way how to debug the JSON output?

**Comment by calexandru2018** [comment]
Not really, you could though paste the output in a pastebin or something similar and share the output

**Comment by t3rmix** [comment]
Im not sure which output you mean? 

To be clear, when i tried to connect
```
$ protonvpn-cli c -r
Setting up ProtonVPN.

An unknown error has occured. Please ensure that you have internet connectivity.
If the issue persists, please contact support.
```
The only one ouput which i get is from ~./cache/protonvpn/logs/protonvpn-cli.log (i sent whole log in previous message)

The error comes from `cli_wrapper.py — ERROR — connect:227 — Expecting value: line 1 column 1 (char 0)` i supposed it's because non valid json response.

**Comment by calexandru2018** [comment]
The content of cached_serverlist.json

**Comment by t3rmix** [comment]
I don't have this file, or it's in different location?
```
ls -a ~/.cache/protonvpn/logs/
.                            protonvpn-dbus-wrapper.log
..                           protonvpn-gui.log
network_manager.service.log  protonvpn.log
protonvpn-cli.log            protonvpn_reconnect.service.log
protonvpn-daemon.log
``

**Comment by calexandru2018** [comment]
Hey @t3rmix, please contact support at: https://protonvpn.com/support-form

**Comment by 5mutawa** [comment]
Running ```pip install jinja2``` fixed the issue for me. I also had to keep nm-applet running for protonvpn to work.
