### ISSUE TITLE
Unable to login

### ISSUE THREAD

**Issue by Delan168** [ProtonVPN/linux-cli#37]
Fresh install from AUR on Manjaro, I get:

> protonvpn-cli login username
> Traceback (most recent call last):
>   File "/usr/bin/protonvpn-cli", line 33, in <module>
>     sys.exit(load_entry_point('protonvpn-cli==3.7.2', 'console_scripts', 'protonvpn-cli')())
>   File "/usr/bin/protonvpn-cli", line 25, in importlib_load_entry_point
>     return next(matches).load()
> StopIteration

What other information may be needed to solve this?

**Comment by Delan168** [comment]
Duplicate of https://github.com/ProtonVPN/linux-cli/issues/20.
