### ISSUE TITLE
nm_client_mixin.py — ERROR — __dynamic_callback:124 — Exception: 'remove' KeyError: 'remove'

### ISSUE THREAD

**Issue by mingchen** [ProtonVPN/linux-cli#45]
OS: Debian 10 Buster 64bit

```
$ protonvpn-cli -v

ProtonVPN CLI v3.8.0 (protonvpn-nm-lib v3.3.2; proton-client v0.5.1)
```

`protonvpn-cli connect` report following error:

```
Unable to connect to ProtonVPN: ProtonVPN connection failed due to unknown reason.
```

Related log:

```
$ tail -n 20 ~/.cache/protonvpn/logs/protonvpn.log
13:32:14,733 — killswitch.py — INFO — update_connection_status:531 — Tracker info: {'pvpn-killswitch': {<KillSwitchInterfaceTrackerEnum.EXISTS: 0>: False, <KillSwitchInterfaceTrackerEnum.IS_RUNNING: 1>: False}, 'pvpn-routed-killswitch': {<KillSwitchInterfaceTrackerEnum.EXISTS: 0>: False, <KillSwitchInterfaceTrackerEnum.IS_RUNNING: 1>: False}}
13:32:14,752 — killswitch.py — INFO — update_connection_status:531 — Tracker info: {'pvpn-killswitch': {<KillSwitchInterfaceTrackerEnum.EXISTS: 0>: False, <KillSwitchInterfaceTrackerEnum.IS_RUNNING: 1>: False}, 'pvpn-routed-killswitch': {<KillSwitchInterfaceTrackerEnum.EXISTS: 0>: False, <KillSwitchInterfaceTrackerEnum.IS_RUNNING: 1>: False}}
13:32:14,753 — nm_client.py — INFO — __get_protonvpn_connection:173 — Getting VPN from "NetworkManagerConnectionTypeEnum.ACTIVE" connections
13:32:14,753 — nm_client.py — INFO — __get_protonvpn_connection:209 — VPN connection: <NM.RemoteConnection object at 0x7f2a64708f30 (NMRemoteConnection at 0x1a06300)>
13:32:14,753 — nm_client_mixin.py — INFO — _remove_connection_async:45 — Removing VPN connection
13:32:14,766 — nm_client_mixin.py — INFO — __dynamic_callback:90 — Callback type: "remove"
13:32:14,766 — nm_client_mixin.py — ERROR — __dynamic_callback:124 — Exception: 'remove'
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/protonvpn_nm_lib/core/connection_backend/nm_client/nm_client_mixin.py", line 117, in __dynamic_callback
    (callback_type_dict[callback_type]["finish_function"])(result)
KeyError: 'remove'
13:32:14,767 — nm_client.py — INFO — _post_disconnect:232 — Running post disconnect.
13:32:14,767 — dbus_reconnect.py — INFO — stop_daemon_reconnector:74 — Stopping daemon reconnector
13:32:14,767 — dbus_reconnect.py — INFO — check_daemon_reconnector_status:122 — Checking daemon reconnector status
13:32:14,777 — ipv6_leak_protection.py — INFO — manage:54 — Manage IPV6: KillSwitchActionEnum.DISABLE
13:32:14,779 — ipv6_leak_protection.py — INFO — get_status_connectivity_check:260 — Conn check available (0) - Conn check enabled (0)
13:32:14,788 — ipv6_leak_protection.py — INFO — update_connection_status:219 — IPv6 status: {'pvpn-ipv6leak-protection': {<KillSwitchInterfaceTrackerEnum.EXISTS: 0>: True, <KillSwitchInterfaceTrackerEnum.IS_RUNNING: 1>: False}}
13:32:14,788 — ipv6_leak_protection.py — INFO — remove_leak_protection:108 — Removing IPv6 leak protection
13:32:14,799 — ipv6_leak_protection.py — INFO — update_connection_status:219 — IPv6 status: {'pvpn-ipv6leak-protection': {<KillSwitchInterfaceTrackerEnum.EXISTS: 0>: True, <KillSwitchInterfaceTrackerEnum.IS_RUNNING: 1>: False}}
13:32:14,869 — default_connection_metadata.py — INFO — save_connect_time:69 — Saved connected time to file
```

**Comment by allora** [comment]
Same on Archlinux.

**Comment by calexandru2018** [comment]
Hey @mingchen 

The network Manager logs would help here more.

**Comment by allora** [comment]
fwiw this is what mine looks like: 
```Aug 15 23:52:13 rufus NetworkManager[95345]: <info>  [1629096733.9204] vpn-connection[0x560a8ced26f0,d28d8fc0-5be1-437d-a4f6-1c3a07807016,"ProtonVPN CH-US#1",0]: Started the VPN service, PID 96756
Aug 15 23:52:13 rufus NetworkManager[95345]: <info>  [1629096733.9233] vpn-connection[0x560a8ced26f0,d28d8fc0-5be1-437d-a4f6-1c3a07807016,"ProtonVPN CH-US#1",0]: Saw the service appear; activating connection
Aug 15 23:52:13 rufus NetworkManager[95345]: <error> [1629096733.9253] vpn-connection[0x560a8ced26f0,d28d8fc0-5be1-437d-a4f6-1c3a07807016,"ProtonVPN CH-US#1",0]: Failed to request VPN secrets #3: No agents were available for this request.
Aug 15 23:52:13 rufus NetworkManager[95345]: <info>  [1629096733.9257] vpn-connection[0x560a8ced26f0,d28d8fc0-5be1-437d-a4f6-1c3a07807016,"ProtonVPN CH-US#1",0]: VPN plugin: state changed: stopped (6)```

**Comment by mingchen** [comment]
I have similar `No agents` error like allora mentioned above.

**Comment by giraudan** [comment]
Same issue here on Arch

`protonvpn-cli --version`

```
ProtonVPN CLI v3.8.0 (protonvpn-nm-lib v3.3.2; proton-client v0.5.1)
```

`protonvpn.log`

```
2021-09-18 16:40:13,953 — nm_client_mixin.py — ERROR — __dynamic_callback:124 — Exception: 'remove'
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/protonvpn_nm_lib/core/connection_backend/nm_client/nm_client_mixin.py", line 117, in __dynamic_callback
    (callback_type_dict[callback_type]["finish_function"])(result)
KeyError: 'remove'
```

`journalctl -u NetworkManager.service`

```
Sep 18 16:40:14 frypan NetworkManager[628]: <error> [1631950814.3353] vpn-connection[0x5596b3ee0790,927>
```

**Comment by allora** [comment]
So, after some fiddling, i discovered that a few things have to be true:

1. You need network manager up and running (systemctl start/enable... I use a wired connection so i didnt have any network manager stuff initially, so my config might have been off)
2. You need a spot for system tray things to live (note I use bspwm, so didnt have anything like this setup as i dont use it, installed stalonetray)
3. You MUST HAVE nm-applet installed and running

It took me a reboot too, but i suspect if you have loaded things up in the right way the first time, its ok. After that, my protonvpn client ran fine (both gui and cli)

Kinda sucky that a cli client requires the nm-applet system tray app :|

**Comment by bugrasan** [comment]
i had the same issue after upgrading from a previous version of protonvpn (to protonvpn-cli).

@allora thanks for the hint, the issue was that `nm-applet` wasn't running; saw the issue with unauthentication network-manager in `journalctl --system -r` since the protonvpn logs (in `~/.cache/protonvpn/logs/` doesn't show anything valuable at all).

btw, using `nm-applet --indicator` on swaywm due to this [issue](https://github.com/swaywm/sway/pull/6249).

lost so much time because of a non-sense gui dependency that isn't mentioned anywhere :angry:

**Comment by allora** [comment]
@bugrasan agree, the documentation of all the dependencies needed for protonvpn is incredibly lacking. Recently I discovered you also need open resolve installed and configured in order for it to properly update your DNS upon connection to protonvpn, else sometimes you could connect to protonVPN and get leaky DNS...

Overall, pretty disappointed in the poor linux support. A lot of assumptions about the system are made that might not always be true.

**Comment by bugrasan** [comment]
just for the sake of the next poor soul who will try:
i also noticed that it requires 'gnome-keyring' and is not able to utilise 'kwallet'.
`protonvpn-cli login <username>` works fine with kwallet alone, but you won't be able to connect afterwards unless you install 'gnome-keyring'

**Comment by xonq** [comment]
the dependency web is nearly impossible to navigate for arch. I had to install several independent pypi packages, sequentially install 4 different protonvpn dependencies, `nm-applet`, activate `NetworkManager`, AND STILL DON'T have it working on Arch. this is ridiculous.

**Comment by sbsaylors** [comment]
Currently:
Ubuntu 20
Installed nm-applet - and running.
verified Network Manager - good
Installed gnome-keyring

able to login from proton-cli successfully.

When app launches? The absolutely worthless and insane error message: unknown error.  Holy smokes.... :(

**Comment by lumarius** [comment]
I also had this issue. @allora's solution above, i.e. enabling networkmanager and starting nm-applet, resolved the issue, but I would hope to get rid of this seemingly excessive latter dependency for a CLI program, and at least a more descriptive error on the former.

**Comment by NunoSempere** [comment]
Also having this issue, when running in xmonad. Pretty wild. I was able to solve this by just running nm-applet in the background, wastefully, doing nothing. 

My suggestion is that it be factored out. See also this: <https://github.com/ProtonVPN/linux-cli/issues/62> related issue.

**Comment by MtlSnk** [comment]
All previously mentioned fixes didn't work for me, so I just wanted to share I fixed it by installing `NetworkManager-openvpn-gnome`.

For me, `nm-applet` was seemingly functioning properly, but my system was missing `/usr/libexec/nm-openvpn-auth-dialog`. Which I figured out after running `nm-applet` in the foreground, logging in and attempting to connect to a VPN server. \
The following error message was thrown:

```
(nm-applet:8794): nm-applet-WARNING **: 22:40:53.317: Failed to execute child process “/usr/libexec/nm-openvpn-auth-dialog” (No such file or directory)
```

FWIW, my system:

- Fedora 36
- i3wm
- protonvpn-cli v3.13.0 (protonvpn-nm-lib v3.14.0; proton-client v0.7.1)

**Comment by ojsl1** [comment]
<details>
<summary>I was getting these errors before enabling KWallet:</summary>

```
ERROR:dbus.proxies:Introspect error on :1.81:/modules/kwalletd5: dbus.exceptions.DBusException: org.freedesktop.DBus.Error.NoReply: Message recipient disconnected from message bus without replying
ERROR:protonvpn:Unable to select keyring.backends.kwallet.DBusKeyring (priority: 5.1) backend
Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/keyring/backends/kwallet.py", line 98, in connected
    self.handle = self.iface.open(self.iface.networkWallet(), wId, self.appid)
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/dbus/proxies.py", line 72, in __call__
    return self._proxy_method(*args, **keywords)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/dbus/proxies.py", line 141, in __call__
    return self._connection.call_blocking(self._named_service,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/dbus/connection.py", line 634, in call_blocking
    reply_message = self.send_message_with_reply_and_block(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
dbus.exceptions.DBusException: org.freedesktop.DBus.Error.ServiceUnknown: The name :1.81 was not provided by any .service files

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/protonvpn_nm_lib/core/keyring/linuxkeyring.py", line 121, in _ensure_backend_is_working
    self.__keyring_backend.get_password(
  File "/usr/lib/python3.11/site-packages/keyring/backends/kwallet.py", line 109, in get_password
    if not self.connected(service):
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/keyring/backends/kwallet.py", line 100, in connected
    raise InitError('Failed to open keyring: %s.' % e)
keyring.errors.InitError: Failed to open keyring: org.freedesktop.DBus.Error.ServiceUnknown: The name :1.81 was not provided by any .service files.
INFO:protonvpn:Using "<class 'protonvpn_nm_lib.core.keyring.linuxkeyring.KeyringBackendLinuxSecretService'>" keyring
INFO:protonvpn:Using "<class 'protonvpn_nm_lib.core.keyring.textfilekeyring.KeyringBackendJsonFiles'>" keyring
INFO:protonvpn-gui:Setting up dashboard images and icons
INFO:protonvpn-gui:Setting up css
INFO:protonvpn-gui:Setting up actions
INFO:protonvpn-gui:Window to display <dashboard.DashboardView object at 0x7f9399b21300 (DashboardView at 0x55895b782860)>
INFO:protonvpn:Nofitications are empty: []
INFO:protonvpn:Metadata backend: <class 'protonvpn_nm_lib.core.metadata.netzone.default.DefaultNetzone'>
INFO:protonvpn:Fetching loads
INFO:protonvpn:Ensure that alternative routing can be skipped
/usr/lib/python3.11/site-packages/protonvpn_nm_lib/core/connection_backend/nm_client/nm_client_mixin.py:11: Warning: g_main_context_push_thread_default: assertion 'acquired_context' failed
  nm_client = NM.Client.new(None)
/usr/lib/python3.11/site-packages/protonvpn_nm_lib/core/connection_backend/nm_client/nm_client_mixin.py:11: Warning: g_main_context_pop_thread_default: assertion 'g_queue_peek_head (stack) == context' failed
  nm_client = NM.Client.new(None)
INFO:protonvpn:Connection backend: <class 'protonvpn_nm_lib.core.connection_backend.nm_client.nm_client.NetworkManagerClient'>
INFO:protonvpn:Template hash "0ee69d81c3d7a57244a28ec168d63427907434d79753a0542c9b680db8f99529"
INFO:protonvpn:Generated hash at runtime "0ee69d81c3d7a57244a28ec168d63427907434d79753a0542c9b680db8f99529"
INFO:protonvpn:Getting VPN from "NetworkManagerConnectionTypeEnum.ACTIVE" connections
INFO:protonvpn:VPN connection: None
INFO:protonvpn:Active Proton VPN connection could not be found. Switiching to alternative routing.
INFO:protonvpn:Checking for internet connectivity
INFO:protonvpn:Getting VPN from "NetworkManagerConnectionTypeEnum.ACTIVE" connections
INFO:protonvpn:VPN connection: None
INFO:protonvpn:Ensure that alternative routing can be skipped
INFO:protonvpn:Getting VPN from "NetworkManagerConnectionTypeEnum.ACTIVE" connections
INFO:protonvpn:VPN connection: None
INFO:protonvpn:Active Proton VPN connection could not be found. Switiching to alternative routing.
INFO:protonvpn:Getting VPN from "NetworkManagerConnectionTypeEnum.ACTIVE" connections
INFO:protonvpn:VPN connection: None
```

</details>

<details>
<summary>These two also appeared on my journal every time I got a popup that was asking to "provide the secrets for the vpn connection"; closing the popup or entering a blank password resulted in the VPNConnectionStateEnum.NEEDS_CREDENTIALS error</summary>

```
plasmashell[58360]: INFO:protonvpn:State: VPNConnectionStateEnum.BEING_ESTABLISHED - Reason: VPNConnectionReasonEnum.NOT_PROVIDED
plasmashell[58360]: INFO:protonvpn:State: VPNConnectionStateEnum.NEEDS_CREDENTIALS - Reason: VPNConnectionReasonEnum.NOT_PROVIDED
```

</details>

It seems to work now after:
1) Installing `libappindicator-gtk3` and `gnome-shell-extension-appindicator` for the tray icon as per https://protonvpn.com/support/official-linux-client-arch/
2) From system settings enabling the "KDE wallet subsystem" and ticking the box "Use KWallet for the Secret Service interface"
3) And rebooting

<details>
<summary>Now after having done the above to get it working I do still get these red herrings on launch </summary>

```
 /usr/lib/python3.9/site-packages/protonvpn_nm_lib/core/connection_backend/nm_client/nm_client_mixin.py:11: Warning: g_main_context_push_thread_default: assertion 'acquired_context' failed
   nm_client = NM.Client.new(None)
 /usr/lib/python3.9/site-packages/protonvpn_nm_lib/core/connection_backend/nm_client/nm_client_mixin.py:11: Warning: g_main_context_pop_thread_default: assertion 'g_queue_peek_head (stack) == context' failed
   nm_client = NM.Client.new(None)
```

</details>

- Manjaro
- KDE

**Comment by JiriChara** [comment]
I had the same issue on Arch Linux and in my case deleting some conflicting VPN connections in: `/etc/NetworkManager/VPN` helped.
