### ISSUE TITLE
Error while connecting - TypeError: __init__() got an unexpected keyword argument 'log_dir_path'

### ISSUE THREAD

**Issue by varun-jois** [ProtonVPN/linux-cli#54]
I'm having difficulties connecting after updating to the current version. I'm not sure what version I was using before but on Sunday evening (EST) I wasn't having this problem. Here is the traceback:

$ protonvpn-cli c
Traceback (most recent call last):
  File "/usr/bin/protonvpn-cli", line 11, in <module>
    load_entry_point('protonvpn-cli==3.10.1', 'console_scripts', 'protonvpn-cli')()
  File "/usr/lib/python3/dist-packages/protonvpn_cli/main.py", line 21, in main
    ProtonVPNCLI()
  File "/usr/lib/python3/dist-packages/protonvpn_cli/cli.py", line 65, in __init__
    res = getattr(self, args.command)()
  File "/usr/lib/python3/dist-packages/protonvpn_cli/cli.py", line 71, in c
    return self.connect()
  File "/usr/lib/python3/dist-packages/protonvpn_cli/cli.py", line 133, in connect
    return self.cli_wrapper.connect(args)
  File "/usr/lib/python3/dist-packages/protonvpn_cli/cli_wrapper.py", line 186, in connect
    if not self.protonvpn.check_session_exists():
  File "/usr/lib/python3/dist-packages/protonvpn_nm_lib/api.py", line 322, in check_session_exists
    return self._env.api_session.is_valid
  File "/usr/lib/python3/dist-packages/protonvpn_nm_lib/core/environment.py", line 54, in api_session
    self.__api_session = APISession()
  File "/usr/lib/python3/dist-packages/protonvpn_nm_lib/core/session/session.py", line 206, in __init__
    self.__session_create()
  File "/usr/lib/python3/dist-packages/protonvpn_nm_lib/core/session/session.py", line 233, in __session_create
    tls_pinning=self._enforce_pinning,
TypeError: __init__() got an unexpected keyword argument 'log_dir_path'

**Comment by varun-jois** [comment]
I had to manually update python3-proton-client to v0.7.1 and now it works.

**Comment by 108806** [comment]
Still got the same error, reinstalling didn't help. 

`ProtonVPN CLI v3.11.0 (protonvpn-nm-lib v3.7.0; proton-client v0.5.1)
Linux 5.13.0-30-generic #33~20.04.1-Ubuntu SMP Mon Feb 7 14:25:10 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux`

`Traceback (most recent call last):
  File "/usr/bin/protonvpn-cli", line 11, in <module>
    load_entry_point('protonvpn-cli==3.11.0', 'console_scripts', 'protonvpn-cli')()
  File "/usr/lib/python3/dist-packages/protonvpn_cli/main.py", line 21, in main
    ProtonVPNCLI()
  File "/usr/lib/python3/dist-packages/protonvpn_cli/cli.py", line 65, in __init__
    res = getattr(self, args.command)()
  File "/usr/lib/python3/dist-packages/protonvpn_cli/cli.py", line 162, in login
    return self.cli_wrapper.login(args.username)
  File "/usr/lib/python3/dist-packages/protonvpn_cli/cli_wrapper.py", line 63, in login
    if self.protonvpn.check_session_exists():
  File "/usr/lib/python3/dist-packages/protonvpn_nm_lib/api.py", line 344, in check_session_exists
    return self._env.api_session.is_valid
  File "/usr/lib/python3/dist-packages/protonvpn_nm_lib/core/environment.py", line 55, in api_session
    self.__api_session = APISession()
  File "/usr/lib/python3/dist-packages/protonvpn_nm_lib/core/session/session.py", line 211, in __init__
    self.__session_create()
  File "/usr/lib/python3/dist-packages/protonvpn_nm_lib/core/session/session.py", line 232, in __session_create
    self.__proton_api = Session(
TypeError: __init__() got an unexpected keyword argument 'log_dir_path`

**Comment by hotstaff** [comment]
I I am also encountering the same error. I'm not sure what caused the error.
I hope this topic will be reopened.

**Comment by chutchi2** [comment]
Yeah I don't know what is going on, but @hotstaff your solution worked for me
