### ISSUE TITLE
Unable to Launch Session

### ISSUE THREAD

**Issue by CPete88** [ProtonVPN/linux-cli#56]
I am not able to launch the Linux CLI or App. I get the following error when I try to run `protonvpn` or  `protonvpn-cli login <username>`. Since I use SUSE 15.3, I build this CLI tool along with the `protonvpn-nm-lib` package on my machine.

Versions I built:
protonvpn-nm-lib version I built: 3.6.1
protonvpn-cli version I built: 3.10.1

`protonvpn-cli login <username>` output:
```
Traceback (most recent call last):
  File "/usr/bin/protonvpn-cli", line 11, in <module>
    load_entry_point('protonvpn-cli==3.10.1', 'console_scripts', 'protonvpn-cli')()
  File "/usr/lib/python3.6/site-packages/protonvpn_cli-3.10.1-py3.6.egg/protonvpn_cli/main.py", line 21, in main
  File "/usr/lib/python3.6/site-packages/protonvpn_cli-3.10.1-py3.6.egg/protonvpn_cli/cli.py", line 65, in __init__
  File "/usr/lib/python3.6/site-packages/protonvpn_cli-3.10.1-py3.6.egg/protonvpn_cli/cli.py", line 162, in login
  File "/usr/lib/python3.6/site-packages/protonvpn_cli-3.10.1-py3.6.egg/protonvpn_cli/cli_wrapper.py", line 63, in login
  File "/usr/lib/python3.6/site-packages/protonvpn_nm_lib-3.6.1-py3.6.egg/protonvpn_nm_lib/api.py", line 322, in check_session_exists
    return self._env.api_session.is_valid
  File "/usr/lib/python3.6/site-packages/protonvpn_nm_lib-3.6.1-py3.6.egg/protonvpn_nm_lib/core/environment.py", line 54, in api_session
    self.__api_session = APISession()
  File "/usr/lib/python3.6/site-packages/protonvpn_nm_lib-3.6.1-py3.6.egg/protonvpn_nm_lib/core/session/session.py", line 206, in __init__
    self.__session_create()
  File "/usr/lib/python3.6/site-packages/protonvpn_nm_lib-3.6.1-py3.6.egg/protonvpn_nm_lib/core/session/session.py", line 233, in __session_create
    tls_pinning=self._enforce_pinning,
TypeError: __init__() got an unexpected keyword argument 'log_dir_path'
```
`protonvpn` output:
```
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/protonvpn_gui-1.6.0-py3.6.egg/protonvpn_gui/main.py", line 261, in do_activate
    if not protonvpn.check_session_exists():
  File "/usr/lib/python3.6/site-packages/protonvpn_nm_lib-3.6.1-py3.6.egg/protonvpn_nm_lib/api.py", line 322, in check_session_exists
    return self._env.api_session.is_valid
  File "/usr/lib/python3.6/site-packages/protonvpn_nm_lib-3.6.1-py3.6.egg/protonvpn_nm_lib/core/environment.py", line 54, in api_session
    self.__api_session = APISession()
  File "/usr/lib/python3.6/site-packages/protonvpn_nm_lib-3.6.1-py3.6.egg/protonvpn_nm_lib/core/session/session.py", line 206, in __init__
    self.__session_create()
  File "/usr/lib/python3.6/site-packages/protonvpn_nm_lib-3.6.1-py3.6.egg/protonvpn_nm_lib/core/session/session.py", line 233, in __session_create
    tls_pinning=self._enforce_pinning,
TypeError: __init__() got an unexpected keyword argument 'log_dir_path'
```

**Comment by skymoo** [comment]
Same issue with 3.13.0 installed from source on RHEL9
