### ISSUE TITLE
"connection failed due to unknown reason."

### ISSUE THREAD

**Issue by shmoobalizer** [ProtonVPN/linux-cli#6]
simply trying to connect to a server either manually or via `protonvpn-cli c -f` results in a failure: 
```
Setting up ProtonVPN.
Connecting to ProtonVPN on US-FREE#2 with UDP.

Unable to connect to ProtonVPN: ProtonVPN connection failed due to unknown reason.
```
Environment: 
`OS: Arch Linux x86_64`
`DE: Xfce 4.16`

**Comment by calexandru2018** [comment]
Hey @shmoobalizer 

`sudo journalctl -eu NetworkManager`

Please type this command into the terminal and find the line where NM is "complaining". My suspicion is that it's something similar to “failed to request vpn secrets: No agents were available”, but I might be wrong.

**Comment by tquin** [comment]
Hi @calexandru2018,
I'm seeing similar issues on an Arch machine. Ran a simple `protonvpn-cli c -f` without root, and it looks like it's failing to create/find the tun module and device file:
```
...
NetworkManager[676]: <info>  [1623460950.6133] vpn-connection[0x556c51094340,47d042a5-XXX,"ProtonVPN AU#40",0]: Started the VPN service, PID 43771
NetworkManager[43772]: modprobe: FATAL: Module tun not found in directory /lib/modules/5.12.4-arch1-2
...
nm-openvpn[43776]: [lxc-au-09.protonvpn.com] Peer Connection Initiated with [AF_INET]116.206.231.186:443
nm-openvpn[43776]: NOTE: setsockopt TCP_NODELAY=1 failed
nm-openvpn[43776]: ERROR: Cannot open TUN/TAP dev /dev/net/tun: No such device (errno=19)
nm-openvpn[43776]: Exiting due to fatal error
```

Let me know if I can help with anything else.

**Comment by abhstract** [comment]
Happening on ubuntu 20.04 too.
Don't know why.

**Comment by nivaca** [comment]
Same here with Manjaro:
    Operating System: Manjaro Linux
    KDE Plasma Version: 5.21.5
    KDE Frameworks Version: 5.82.0
    Qt Version: 5.15.2
    Kernel Version: 5.12.11-zen1-1-zen
    OS Type: 64-bit
    Graphics Platform: X11
    Processors: 8 × Intel® Core™ i7-8550U CPU @ 1.80GHz
    Memory: 15,4 GiB of RAM
    Graphics Processor: Mesa Intel® UHD Graphics 620

However, I do not get any errors when inspecting with `sudo journalctl -eu NetworkManager`.

**Comment by calexandru2018** [comment]
Hey all,

With the recent stable release there was a small issue that prevented users from connecting. This has now been solved with the latest release of the library (at time of writing this) 3.3.1. Please update with your package managers.

**Comment by nivaca** [comment]
Thanks, @calexandru2018. That fixed the issue. However, the pvpn-ipv6leak-protection connection never gets connected. Should I file a new issue?

**Comment by Arcadio-Buendia** [comment]
OS: Debian Sid
ProtonVPN CLI v3.7.1 (protonvpn-nm-lib v3.3.1; proton-client v0.5.1)
gnome-keyring: 3.36.0

I ran ProtonVPN with the command:  ```protonvpn-cli c -f``` and it got stuck at 
```Connecting to ProtonVPN on JP-FREE#2 with UDP.```

The error shown by network manager is:
```
NetworkManager[898]: <error> [1624688896.6587] vpn-connection[0x55bb11a862c0,30c830f7-d922-4db3-9284-1ca8e43be37e,"ProtonVPN JP-FREE#2",0]: Failed to request VPN secrets #3: No agents were available for this request.
```
Which you mentioned earlier. Can anything be done by the user?

ProtonVPN Logs give:
```nm_client_mixin.py — ERROR — __dynamic_callback:124 — Exception: NM.Client.activate_connection_finish() takes exactly 2 arguments (1 given)
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/protonvpn_nm_lib/core/connection_backend/nm_client/nm_client_mixin.py", line 117, in __dynamic_callback
    (callback_type_dict[callback_type]["finish_function"])(result)
TypeError: NM.Client.activate_connection_finish() takes exactly 2 arguments (1 given)
```
Finally, pvpn-ipv6leak-protection gets connected, and I lose my internet connection.

**Comment by mingchen** [comment]
The latest release 3.8.0 still have `Exception: NM.Client.activate_connection_finish() takes exactly 2 arguments (1 given)` issue.

```
$ protonvpn-cli -v

ProtonVPN CLI v3.8.0 (protonvpn-nm-lib v3.3.2; proton-client v0.5.1)

$ protonvpn-cli c -r -p tcp
Connecting to ProtonVPN on US-FREE#1 with TCP.

Unable to connect to ProtonVPN: ProtonVPN connection failed due to unknown reason.
```

```
$ tail ~/.cache/protonvpn/logs/protonvpn.log 
nm_client.py — INFO — connect:89 — Starting VPN connection
nm_client.py — INFO — __get_protonvpn_connection:173 — Getting VPN from "NetworkManagerConnectionTypeEnum.ALL" connections
nm_client.py — INFO — __get_protonvpn_connection:209 — VPN connection: <NM.RemoteConnection object at 0x7fa96099ef78 (NMRemoteConnection at 0x29e9320)>
nm_client_mixin.py — INFO — _start_connection_async:29 — Starting VPN connection
nm_client_mixin.py — INFO — __dynamic_callback:90 — Callback type: "start"
nm_client_mixin.py — ERROR — __dynamic_callback:124 — Exception: NM.Client.activate_connection_finish() takes exactly 2 arguments (1 given)
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/protonvpn_nm_lib/core/connection_backend/nm_client/nm_client_mixin.py", line 117, in __dynamic_callback
    (callback_type_dict[callback_type]["finish_function"])(result)
TypeError: NM.Client.activate_connection_finish() takes exactly 2 arguments (1 given)
monitor_vpn_connection_start.py — INFO — vpn_signal_handler:131 — /org/freedesktop/NetworkManager/ActiveConnection/99 is not an active connection.
```

**Comment by prAnjal314** [comment]
> sudo journalctl -eu NetworkManager



> Hey @shmoobalizer
> 
> `sudo journalctl -eu NetworkManager`
> 
> Please type this command into the terminal and find the line where NM is "complaining". My suspicion is that it's something similar to “failed to request vpn secrets: No agents were available”, but I might be wrong.

Yes I get this error, now what should I do? I have 'gnome-keyring' installed and 'kdewallet' too, but disabled kwallet, using

`[Wallet]
Enabled=false
`
in the kwalletrc.
