### ISSUE TITLE
An unknown error has occured. Please ensure that you have internet connectivity. If the issue persists, please contact support.

### ISSUE THREAD

**Issue by acc-galenicum** [ProtonVPN/linux-cli#61]
Hi,
I'm working in a GCP Debian 10 linux machine, no graphic interface.
I installed the protonvpn-stable-release and protonvpn-cli following instructions here: https://protonvpn.com/support/linux-vpn-tool/

I am able to login, but when I try to connect to a proxy (protonvpn-cli c -f) it returns me this error:

**An unknown error has occured. Please ensure that you have internet connectivity.
If the issue persists, please contact support.**

Not much information to understand the error...

I've tried to find solutions and read similar problems, but nothing seems to match exactly my case.

Any help would be appreciated!

**Comment by iMerica** [comment]
Same for me

**Comment by astartav** [comment]
Same for me on Ubuntu 18.04 for protonvpn-cli 3.11.0-7

**Comment by Anglodel** [comment]
It happens to me too, with `ProtonVPN CLI v3.11.1 (protonvpn-nm-lib v3.8.0; proton-client v0.7.1)`.
OS infos:
```
OS: Arch Linux x86_64
Kernel: 5.16.15-arch1-1
WM: i3
```

**Comment by Morion-Self** [comment]
+ archlinux, 5.15.32-1-lts

**Comment by Morion-Self** [comment]
UPD: I had the `networkmanager-strongswan` package installed. 
There was such an error in the logs:
```
2022-03-29 19:32:43,294 — cli_wrapper.py — ERROR — connect:379 — nm-vpn-plugin-error-quark: cannot load plugin "/usr/lib/NetworkManager/libnm-vpn-plugin-strongswan.so": libnma.so.0: cannot open shared object file: No such file or directory (0)
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/protonvpn_cli/cli_wrapper.py", line 277, in connect
    self.protonvpn.setup_connection(
  File "/usr/lib/python3.10/site-packages/protonvpn_nm_lib/api.py", line 153, in setup_connection
    self._env.connection_backend.setup(**data)
  File "/usr/lib/python3.10/site-packages/protonvpn_nm_lib/core/connection_backend/nm_client/nm_client.py", line 51, in setup
    connection, protocol_implementation = NMPlugin.import_vpn_config(
  File "/usr/lib/python3.10/site-packages/protonvpn_nm_lib/core/connection_backend/nm_client/plugin/nm_plugin.py", line 21, in import_vpn_config
    plugin_editor = plugin.load_editor_plugin()
gi.repository.GLib.GError: nm-vpn-plugin-error-quark: cannot load plugin "/usr/lib/NetworkManager/libnm-vpn-plugin-strongswan.so": libnma.so.0: cannot open shared object file: No such file or directory (0)
```

After deleting the `networkmanager-strongswan`, it was possible to connect. But this is not a solution, because I need these package

**Comment by bi7je** [comment]
I have this issue too.
Is this going to be resolved at some point?

**Comment by marekpetak** [comment]
Just installed on Ubuntu server 22.04 LTS (jammy) using Proton VPN CLI v3.12.0 (protonvpn-nm-lib v3.10.0; proton-client v0.7.1) and connecting via UDP connection.
I have tried using renderer in Netplan as NetworkManager, but this made no difference.

```
Setting up Proton VPN.

An unknown error has occured. Please ensure that you have internet connectivity.
If the issue persists, please contact support.
```

**Comment by thramas** [comment]
Just installed on Ubuntu server 20.04.3 LTS using Proton VPN CLI v3.12.0 (protonvpn-nm-lib v3.11.0; proton-client v0.7.1) and connecting via UDP connection. Not able to connect
`Setting up Proton VPN.

An unknown error has occured. Please ensure that you have internet connectivity.
If the issue persists, please contact support.
minion@minion:~$ protonvpn-cli status

No active Proton VPN connection.`

**Comment by bi7je** [comment]
Make sure NetworkManager is running.
That was the problem for me when i got this error.

**Comment by Demetri0** [comment]
Same issue persists for several months. (`Proton VPN CLI v3.12.0 (protonvpn-nm-lib v3.11.0; proton-client v0.7.1)`)

`Linux demetrio 5.4.0-109-generic #123-Ubuntu SMP Fri Apr 8 09:10:54 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux`

Message from newest client (just upgraded) is:
```
$protonvpn-cli c -f

Setting up Proton VPN.
Connecting to Proton VPN on JP-FREE#3 with UDP.

Unable to connect to Proton VPN: Proton VPN connection has been disconnected. Reason: VPNConnectionReasonEnum.UNKNOWN_ERROR
```

Earlier client version just printed:
```
Setting up Proton VPN.

An unknown error has occured. Please ensure that you have internet connectivity.
If the issue persists, please contact support.
```

Legacy cli client:
```
$protonvpn -v
ProtonVPN-CLI v2.2.4
```

Prints next output:
```
$sudo protonvpn c -f

There is already a VPN connection running.
Terminating previous connection...
Connecting to US-FREE#49 via UDP...
[!] There was an error with accessing the ProtonVPN API.
[!] Please make sure your connection is working properly!
[!] HTTP Error Code: 422
```

But looks like it is actually connects, because I was able to get access to blocked resources, while newest versions is not working at all.

**Comment by MuhammedZakir** [comment]
I had this problem recently, and deleting `~/.cache/protonvpn` fixed this. May need to run `protonvpn-cli d` once before/after doing it.

**Comment by Demetri0** [comment]
Deleting `~/.cache/protonvpn` doesn't help.

But I found a logs in this folder:

<details>
<summary>protonvpn-cli.log</summary>
<pre><code>
2022-07-03 08:00:47,613 — cli.py — INFO — __init__:17 — 
-------------------------------------------------

-----------	Initialized protonvpn-cli	-----------

-------------------------------------------------
2022-07-03 08:00:47,613 — cli.py — INFO — __init__:29 — Proton VPN CLI v3.12.0 (protonvpn-nm-lib v3.11.0; proton-client v0.7.1)
2022-07-03 08:00:47,616 — cli.py — INFO — __init__:64 — CLI command: Namespace(command='d', get_logs=False, help=False, version=False)
2022-07-03 08:00:54,738 — cli.py — INFO — __init__:17 — 
-------------------------------------------------

-----------	Initialized protonvpn-cli	-----------

-------------------------------------------------
2022-07-03 08:00:54,738 — cli.py — INFO — __init__:29 — Proton VPN CLI v3.12.0 (protonvpn-nm-lib v3.11.0; proton-client v0.7.1)
2022-07-03 08:00:54,740 — cli.py — INFO — __init__:64 — CLI command: Namespace(command='c', get_logs=False, help=False, version=False)
2022-07-03 08:00:54,741 — cli.py — INFO — connect:128 — Options: Namespace(cc=None, fastest=True, help=False, p2p=False, protocol=None, random=False, sc=False, servername=None, tor=False)
2022-07-03 08:01:05,219 — cli_wrapper.py — ERROR — connect:379 — No internet connection. Please make sure you are connected and retry.
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 159, in _new_conn
    conn = connection.create_connection(
  File "/usr/lib/python3/dist-packages/urllib3/util/connection.py", line 84, in create_connection
    raise err
  File "/usr/lib/python3/dist-packages/urllib3/util/connection.py", line 74, in create_connection
    sock.connect(sa)
OSError: [Errno 113] No route to host

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 665, in urlopen
    httplib_response = self._make_request(
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 376, in _make_request
    self._validate_conn(conn)
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 996, in _validate_conn
    conn.connect()
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 314, in connect
    conn = self._new_conn()
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 171, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.VerifiedHTTPSConnection object at 0x7fcc3f1558e0>: Failed to establish a new connection: [Errno 113] No route to host

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 719, in urlopen
    retries = retries.increment(
  File "/usr/lib/python3/dist-packages/urllib3/util/retry.py", line 436, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='protonstatus.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7fcc3f1558e0>: Failed to establish a new connection: [Errno 113] No route to host'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/protonvpn_nm_lib/core/utilities.py", line 26, in ensure_internet_connection_is_available
    requests.get(
  File "/usr/lib/python3/dist-packages/requests/api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='protonstatus.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7fcc3f1558e0>: Failed to establish a new connection: [Errno 113] No route to host'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/protonvpn_cli/cli_wrapper.py", line 277, in connect
    self.protonvpn.setup_connection(
  File "/usr/lib/python3/dist-packages/protonvpn_nm_lib/api.py", line 93, in setup_connection
    self._utils.ensure_internet_connection_is_available()
  File "/usr/lib/python3/dist-packages/protonvpn_nm_lib/core/utilities.py", line 38, in ensure_internet_connection_is_available
    raise exceptions.NetworkConnectionError(
protonvpn_nm_lib.exceptions.NetworkConnectionError: No internet connection. Please make sure you are connected and retry.
</code></pre>
</details>

```
$ping protonstatus.com

PING protonstatus.com (188.114.97.1) 56(84) bytes of data.
64 bytes from 188.114.97.1 (188.114.97.1): icmp_seq=1 ttl=53 time=66.0 ms
64 bytes from 188.114.97.1 (188.114.97.1): icmp_seq=2 ttl=53 time=65.9 ms
^C
--- protonstatus.com ping statistics ---
2 packets transmitted, 2 received, 0% packet loss, time 1001ms
rtt min/avg/max/mdev = 65.923/65.985/66.047/0.062 ms
```

**Comment by MuhammedZakir** [comment]
IIRC, I also had a similiar issue. ProtonVPN logs it couldn't connect to ProtonVPN server when it works fine in other devices connected to same network, and it started working when I deleted the cache folder. So there's something really wrong with the library related to connectivity.

**Comment by arakakiv** [comment]
Same problem in ChromeOS.

**Comment by inconspicuous99** [comment]
```python
2022-08-05 07:43:19,135 — cli.py — INFO — __init__:29 — Proton VPN CLI v3.12.0 (protonvpn-nm-lib v3.11.0; proton-client v0.7.1)
2022-08-05 07:43:19,137 — cli.py — INFO — __init__:64 — CLI command: Namespace(command='c', get_logs=False, help=False, version=False)
2022-08-05 07:43:19,137 — cli.py — INFO — connect:128 — Options: Namespace(cc=None, fastest=True, help=False, p2p=False, protocol='udp', random=False, sc=False, servername=None, tor=False)
2022-08-05 07:43:21,356 — cli_wrapper.py — ERROR — connect:379 — cannot import name 'soft_unicode' from 'markupsafe' (/home/a112/.local/lib/python3.8/site-packages/markupsafe/__init__.py)
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/protonvpn_cli/cli_wrapper.py", line 277, in connect
    self.protonvpn.setup_connection(
  File "/usr/lib/python3/dist-packages/protonvpn_nm_lib/api.py", line 153, in setup_connection
    configuration = physical_server.get_configuration(_protocol)
  File "/usr/lib/python3/dist-packages/protonvpn_nm_lib/core/servers/list.py", line 53, in get_configuration
    from ..vpn import VPNConfiguration
  File "/usr/lib/python3/dist-packages/protonvpn_nm_lib/core/vpn/__init__.py", line 1, in <module>
    from .vpn_configuration import VPNConfiguration
  File "/usr/lib/python3/dist-packages/protonvpn_nm_lib/core/vpn/vpn_configuration.py", line 5, in <module>
    import jinja2
  File "/usr/lib/python3/dist-packages/jinja2/__init__.py", line 33, in <module>
    from jinja2.environment import Environment, Template
  File "/usr/lib/python3/dist-packages/jinja2/environment.py", line 15, in <module>
    from jinja2 import nodes
  File "/usr/lib/python3/dist-packages/jinja2/nodes.py", line 23, in <module>
    from jinja2.utils import Markup
  File "/usr/lib/python3/dist-packages/jinja2/utils.py", line 656, in <module>
    from markupsafe import Markup, escape, soft_unicode
ImportError: cannot import name 'soft_unicode' from 'markupsafe' (/home/a112/.local/lib/python3.8/site-packages/markupsafe/__init__.py)
2022-08-05 07:44:14,912 — cli.py — INFO — __init__:17 —

**Comment by inconspicuous99** [comment]
```python
2022-08-05 07:43:19,135 — cli.py — INFO — __init__:29 — Proton VPN CLI v3.12.0 (protonvpn-nm-lib v3.11.0; proton-client v0.7.1)
2022-08-05 07:43:19,137 — cli.py — INFO — __init__:64 — CLI command: Namespace(command='c', get_logs=False, help=False, version=False)
2022-08-05 07:43:19,137 — cli.py — INFO — connect
2022-08-05 07:43:21,356 — cli_wrapper.py — ERROR — connect:379 — cannot import name 'soft_unicode' from 'markupsafe' (/home/a112/.local/lib/python3.8/site-packages/markupsafe/__init__.py)
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/protonvpn_cli/cli_wrapper.py", line 277, in connect
    self.protonvpn.setup_connection(
  File "/usr/lib/python3/dist-packages/protonvpn_nm_lib/api.py", line 153, in setup_connection
    configuration = physical_server.get_configuration(_protocol)
  File "/usr/lib/python3/dist-packages/protonvpn_nm_lib/core/servers/list.py", line 53, in get_configuration
    from ..vpn import VPNConfiguration
  File "/usr/lib/python3/dist-packages/protonvpn_nm_lib/core/vpn/__init__.py", line 1, in <module>
    from .vpn_configuration import VPNConfiguration
  File "/usr/lib/python3/dist-packages/protonvpn_nm_lib/core/vpn/vpn_configuration.py", line 5, in <module>
    import jinja2
  File "/usr/lib/python3/dist-packages/jinja2/__init__.py", line 33, in <module>
    from jinja2.environment import Environment, Template
  File "/usr/lib/python3/dist-packages/jinja2/environment.py", line 15, in <module>
    from jinja2 import nodes
  File "/usr/lib/python3/dist-packages/jinja2/nodes.py", line 23, in <module>
    from jinja2.utils import Markup
  File "/usr/lib/python3/dist-packages/jinja2/utils.py", line 656, in <module>
    from markupsafe import Markup, escape, soft_unicode
ImportError: cannot import name 'soft_unicode' from 'markupsafe' (/home/a112/.local/lib/python3.8/site-packages/markupsafe/__init__.py)
2022-08-05 07:44:14,912 — cli.py — INFO — __init__:17 — 
```

[https://github.com/dbt-labs/dbt-core/issues/4745#issuecomment-1043953804](https://github.com/dbt-labs/dbt-core/issues/4745#issuecomment-1043953804)

![image](https://user-images.githubusercontent.com/83731823/183030139-e991e84b-16e1-4eb3-8074-2b105e243301.png)

Doing ^ and re-running the CLI / restarting my  GUI worked for me.

**Comment by braintxx** [comment]
Setting up Proton VPN.
An unknown error has occured. Please ensure that you have internet connectivity.
If the issue persists, please contact support.

same..

**Comment by cruzerngz** [comment]
> I had this problem recently, and deleting `~/.cache/protonvpn` fixed this. May need to run `protonvpn-cli d` once before/after doing it.

This works for me. I deleted and ran the protonvpn-cli after and it connects now.

**Comment by martinezhermes** [comment]
has anyone got this working?

**Comment by arakakivl** [comment]
Some few days ago I had this issue again, but in arch linux then. Solved by running **nm-applet** before trying to connect to it.

**Comment by pghpete** [comment]
I have this same issue on fedora 36. Oddly it works fine from a terminal window within gnome on the box... but if I ssh in to that same box and try the same protonvpn-cli command it fails with this message...

`Setting up Proton VPN.

An unknown error has occured. Please ensure that you have internet connectivity.
If the issue persists, please contact support.`

The main reason I want to be able to use the cli is so I can ssh into a box and connect it to a vpn so why it doesn't work while sshed in but does work while in a terminal on a box is beyond me.

**Comment by nathant8883** [comment]
> Found a solution to my problem above... (at least on Fedora 35)
> 
> create this file as root, change USER for your user name....
> 
> ```
> cat /var/lib/polkit-1/localauthority/50-local.d/10-network-manager.pkla
> [allow USER to modify all network states and settings]
> Identity=unix-user:USER
> Action=org.freedesktop.NetworkManager.*
> ResultAny=yes
> ResultInactive=yes
> ResultActive=yes
> 
> systemctl restart NetworkManager
> ```

This solution moved me along one step on Ubuntu 22.04.1 LTS Server. However connect command gets stuck connecting to any server.

**Comment by Bodmoor** [comment]
> > Found a solution to my problem above... (at least on Fedora 35)
> > create this file as root, change USER for your user name....
> > ```
> > cat /var/lib/polkit-1/localauthority/50-local.d/10-network-manager.pkla
> > [allow USER to modify all network states and settings]
> > Identity=unix-user:USER
> > Action=org.freedesktop.NetworkManager.*
> > ResultAny=yes
> > ResultInactive=yes
> > ResultActive=yes
> > 
> > systemctl restart NetworkManager
> > ```
> 
> This solution moved me along one step on Ubuntu 22.04.1 LTS Server. However connect command gets stuck connecting to any server.

I am also at this point. Stuck for now...

**Comment by acobster** [comment]
Same for me on Ubuntu Server 22.04 LTS.

Proton version:

```
Proton VPN CLI v3.13.0 (protonvpn-nm-lib v3.14.0; proton-client v0.7.1)
```

System info:

```
$ uname -a
Linux ubuntu 5.19.0-1006-raspi #13-Ubuntu SMP PREEMPT Mon Oct 17 19:03:10 UTC 2022 armv7l armv7l armv7l GNU/Linux
```

**Comment by StevenWegner** [comment]
Same for me. So close. 
`Proton VPN CLI v3.13.0 (protonvpn-nm-lib v3.14.0; proton-client v0.7.1)`

`Linux 5.15.74.2-microsoft-standard-WSL2 #1 SMP Wed Nov 2 19:50:29 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux`

Running Ubuntu in WSL

**Comment by cdorfer** [comment]
Same here (Raspbian GNU/Linux 10). 
Happy I tested the cli-tool before upgrading my plan to ProtonVPN Plus..

**Comment by Demetri0** [comment]
Unfortunately for me, I'm still paying for ProtonVPN Plus... probably it is time to migrate to mulvadvpn...

**Comment by nathant8883** [comment]
I'm just going to leave this here because I did find the answer. ProtonCLI does not support Ubuntu Server. It requires an os with a display.

**Comment by Scripsky** [comment]
> 

I was able to login on ubuntu server, but only directly from the console's terminal and not through ssh. You could try that

**Comment by majjuss** [comment]
> I had this problem recently, and deleting `~/.cache/protonvpn` fixed this. May need to run `protonvpn-cli d` once before/after doing it.

worked for me also, on Ubuntu Mate 20.04 (running in a VM)

**Comment by matjolic** [comment]
I'm running PopOS 22.04, based of Ubuntu LTS, protonvpn-cli is giving my this error right now due to not being able to resolve protonstatus.com. Cross-checked with online tools, and it seems down.

`$ protonvpn-cli -v

Proton VPN CLI v3.13.0 (protonvpn-nm-lib v3.14.0; proton-client v0.7.1)
`

`-------------------------------------------------

-----------	Initialized protonvpn-cli	-----------

-------------------------------------------------
2023-01-09 16:30:04,776 — cli.py — INFO — __init__:29 — Proton VPN CLI v3.13.0 (protonvpn-nm-lib v3.14.0; proton-client v0.7.1)
2023-01-09 16:30:04,779 — cli.py — INFO — __init__:64 — CLI command: Namespace(command='c', version=False, help=False, get_logs=False)
2023-01-09 16:30:04,779 — cli.py — INFO — connect:128 — Options: Namespace(servername=None, fastest=False, random=False, cc='CA', sc=False, p2p=False, tor=False, protocol=None, help=False)
2023-01-09 16:30:05,292 — cli_wrapper.py — ERROR — connect:383 — No internet connection. Please make sure you are connected and retry.
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 169, in _new_conn
    conn = connection.create_connection(
  File "/usr/lib/python3/dist-packages/urllib3/util/connection.py", line 73, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "/usr/lib/python3.10/socket.py", line 955, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -3] Temporary failure in name resolution

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 382, in _make_request
    self._validate_conn(conn)
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 1012, in _validate_conn
    conn.connect()
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 353, in connect
    conn = self._new_conn()
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 181, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x7f38a6738610>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 755, in urlopen
    retries = retries.increment(
  File "/usr/lib/python3/dist-packages/urllib3/util/retry.py", line 574, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='protonstatus.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f38a6738610>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))`

**Comment by horta** [comment]
Protonvpn-cli uses NetworkManager to configure its connection but Ubuntu 22.04 uses systemd-networkd instead, therefore the whole issue.

An option would be to setup ubuntu 22.04 to use systemd-network instead but you will face new issues non-related to protonvpn I believe...

**Comment by lucasjkr** [comment]
Came here to say that I've had no problems with ProtonVPN cli on Fedora, but am having this same issue with Ubuntu Server as everyone else.

From SSH, I get the above error ("An unknown error...")

From console, it actually tries to connect, but just stays there. My screen reads:

`Connecting to Proton VPN on CH-AR#10 with UDP`

I thought it was stuck on that for the past few minutes, but I couldn't even Ctrl-C out of it.

**Comment by hardhu** [comment]
Same for me both with Ubuntu 22.10 and Debian 11 (an unknown error has occurred....), and both using the cli and the gui interface of protonvpn. Has anybody found a fix (besides moving to another linux distribution)?

**Comment by davidalvarezr** [comment]
I had the same problem on my raspberry pi 4 and following this fixed the problem: https://pimylifeup.com/raspberry-pi-network-manager/

**Comment by giuliohome** [comment]
GNU Debian 11 here.
In my case I enabled KDE Portfolio and started KWalletManager.
For me it has been important to delete
```sh
rm ~/.local/bin/protonvpn
```

**Comment by fishyfishphil** [comment]
Still the same today:
`Linux server 5.15.0-73-generic #80-Ubuntu SMP Mon May 15 15:18:26 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux`
`Proton VPN CLI v3.13.0 (protonvpn-nm-lib v3.14.0; proton-client v0.7.1)`

**Comment by Pierstoval** [comment]
Same here, installed in Ubuntu via WSL.

I have no idea on what to do here to fix it 😕

Here are the details:

```
~ ❯ uname -sorp                                                                                                                                                               11:17:01
Linux 5.15.90.1-microsoft-standard-WSL2 x86_64 GNU/Linux

~ ❯ protonvpn-cli --version                                                                                                                                                   11:17:05
Proton VPN CLI v3.13.0 (protonvpn-nm-lib v3.14.0; proton-client v0.7.1)

~ ❯ protonvpn-cli connect --random                                                                                                                                            11:17:08
Setting up Proton VPN.

An unknown error has occured. Please ensure that you have internet connectivity.
If the issue persists, please contact support.

~ ❯ cat ~/.cache/protonvpn/logs/protonvpn-cli.log                                                                                                                           ≡ 11:17:54
2023-07-18 09:17:53,933 — cli.py — INFO — __init__:17 —
-------------------------------------------------

-----------     Initialized protonvpn-cli       -----------

-------------------------------------------------
2023-07-18 09:17:53,933 — cli.py — INFO — __init__:29 — Proton VPN CLI v3.13.0 (protonvpn-nm-lib v3.14.0; proton-client v0.7.1)
2023-07-18 09:17:53,935 — cli.py — INFO — __init__:64 — CLI command: Namespace(command='connect', get_logs=False, help=False, version=False)
2023-07-18 09:17:53,936 — cli.py — INFO — connect:128 — Options: Namespace(cc=None, fastest=False, help=False, p2p=False, protocol=None, random=True, sc=False, servername=None, tor=False)
2023-07-18 09:17:54,758 — cli_wrapper.py — ERROR — connect:383 — g-io-error-quark: Could not connect: No such file or directory (1)
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/protonvpn_cli/cli_wrapper.py", line 277, in connect
    self.protonvpn.setup_connection(
  File "/usr/lib/python3/dist-packages/protonvpn_nm_lib/api.py", line 155, in setup_connection
    self._env.connection_backend.vpn_configuration = configuration
  File "/usr/lib/python3/dist-packages/protonvpn_nm_lib/core/environment.py", line 43, in connection_backend
    from .connection_backend import ConnectionBackend
  File "/usr/lib/python3/dist-packages/protonvpn_nm_lib/core/connection_backend/__init__.py", line 1, in <module>
    from .nm_client import nm_client # noqa
  File "/usr/lib/python3/dist-packages/protonvpn_nm_lib/core/connection_backend/nm_client/nm_client.py", line 16, in <module>
    from .nm_client_mixin import NMClientMixin
  File "/usr/lib/python3/dist-packages/protonvpn_nm_lib/core/connection_backend/nm_client/nm_client_mixin.py", line 10, in <module>
    class NMClientMixin:
  File "/usr/lib/python3/dist-packages/protonvpn_nm_lib/core/connection_backend/nm_client/nm_client_mixin.py", line 11, in NMClientMixin
    nm_client = NM.Client.new(None)
gi.repository.GLib.GError: g-io-error-quark: Could not connect: No such file or directory (1)
```

**Comment by MysticalGrape** [comment]
In case anyone else wasted some time troubleshooting the headless server.
![image](https://github.com/ProtonVPN/linux-cli/assets/8400428/458d83ca-85ba-49b8-8739-7322ca5c4d71)

**Comment by FruitGooseKSP** [comment]
If anyone is still having the "**An unknown error has occured. Please ensure that you have internet connectivity.
If the issue persists, please contact support**" issue, try the python version which can be found at [https://pypi.org/project/protonvpn-cli/](https://pypi.org/project/protonvpn-cli/). 

Instead of using your Proton username and password, you use the OpenVPN username and passwords (found on your ProtonVPN account page ([https://account.protonvpn.com/account](https://account.protonvpn.com/account)) which seems to work correctly (on Ubuntu Server/no GUI/accessing with SSH).

**Comment by asherawelan** [comment]
I am using Ubuntu 22.04 (Jammy Jellyfish) and found this article incredibly helpful and it worked for me.
https://djangocas.dev/blog/linux/troubleshooting-protonvpn-EnableIPv6LeakProtectionError-Unable-to-add-IPv6-leak-protection-connection-interface/

**Comment by ajolibois** [comment]
use https://protonvpn.com/support/linux-openvpn/ procedure to use protonVPN with ubuntu server.

easy to install, and it's work !
