### ISSUE TITLE
i have deleted the old cli and the new one isnt working for some reason

### ISSUE THREAD

**Issue by D0nnieD4rk0** [ProtonVPN/linux-cli#63]
>  We are happy to answer your questions about the code or discuss technical ideas. 
 
Please complete the following checklist (by adding [x]):
- [X] I have searched open and closed issues for duplicates
- [X] This isn't a feature request
- [ ] This is not a report about my app not working as expected

----------------------------------------
i have made sure to delete the old thing and all its files but the new one just refuses to work
now even the old protonvpn-cli-ng is busted and unusable
here's the error log

```text
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/secretstorage/__init__.py", line 72, in dbus_init
    connection = open_dbus_connection()
  File "/usr/lib/python3.10/site-packages/jeepney/io/blocking.py", line 332, in open_dbus_connection
    bus_addr = get_bus(bus)
  File "/usr/lib/python3.10/site-packages/jeepney/bus.py", line 53, in get_bus
    return find_session_bus()
  File "/usr/lib/python3.10/site-packages/jeepney/bus.py", line 42, in find_session_bus
    addr = os.environ['DBUS_SESSION_BUS_ADDRESS']
  File "/usr/lib/python3.10/os.py", line 679, in __getitem__
    raise KeyError(key) from None
KeyError: 'DBUS_SESSION_BUS_ADDRESS'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/protonvpn_nm_lib/core/keyring/linuxkeyring.py", line 21, in __getitem__
    stored_data = self.__keyring_backend.get_password(
  File "/usr/lib/python3.10/site-packages/keyring/backends/SecretService.py", line 78, in get_password
    collection = self.get_preferred_collection()
  File "/usr/lib/python3.10/site-packages/keyring/backends/SecretService.py", line 56, in get_preferred_collection
    bus = secretstorage.dbus_init()
  File "/usr/lib/python3.10/site-packages/secretstorage/__init__.py", line 78, in dbus_init
    raise SecretServiceNotAvailableException(reason) from ex
secretstorage.exceptions.SecretServiceNotAvailableException: Environment variable DBUS_SESSION_BUS_ADDRESS is unset

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/protonvpn-cli", line 33, in <module>
    sys.exit(load_entry_point('protonvpn-cli==3.11.0', 'console_scripts', 'protonvpn-cli')())
  File "/usr/lib/python3.10/site-packages/protonvpn_cli/main.py", line 21, in main
    ProtonVPNCLI()
  File "/usr/lib/python3.10/site-packages/protonvpn_cli/cli.py", line 65, in __init__
    res = getattr(self, args.command)()
  File "/usr/lib/python3.10/site-packages/protonvpn_cli/cli.py", line 71, in c
    return self.connect()
  File "/usr/lib/python3.10/site-packages/protonvpn_cli/cli.py", line 133, in connect
    return self.cli_wrapper.connect(args)
  File "/usr/lib/python3.10/site-packages/protonvpn_cli/cli_wrapper.py", line 186, in connect
    if not self.protonvpn.check_session_exists():
  File "/usr/lib/python3.10/site-packages/protonvpn_nm_lib/api.py", line 344, in check_session_exists
    return self._env.api_session.is_valid
  File "/usr/lib/python3.10/site-packages/protonvpn_nm_lib/core/environment.py", line 55, in api_session
    self.__api_session = APISession()
  File "/usr/lib/python3.10/site-packages/protonvpn_nm_lib/core/session/session.py", line 223, in __init__
    self.__keyring_load_session()
  File "/usr/lib/python3.10/site-packages/protonvpn_nm_lib/core/session/session.py", line 251, in __keyring_load_session
    keyring_data_user = ExecutionEnvironment().keyring[
  File "/usr/lib/python3.10/site-packages/protonvpn_nm_lib/core/keyring/linuxkeyring.py", line 32, in __getitem__
    raise exceptions.KeyringError(e)
protonvpn_nm_lib.exceptions.KeyringError: Environment variable DBUS_SESSION_BUS_ADDRESS is unset
```

**Comment by MuhammedZakir** [comment]
1. How are you running `protonvpn-cli`?
2. Do you get output for `echo $DBUS_SESSION_BUS_ADDRESS`? (e.g. `unix:path=/run/user/1003/bus`)
3. Your OS?
