### ISSUE TITLE
failed to install cli with aur helper (A failure occurred in build().)

### ISSUE THREAD

**Issue by Golam-moula** [ProtonVPN/linux-cli#73]
yay  -Sy protonvpn-cli

```
:: Checking for conflicts...
:: Checking for inner conflicts...
[Aur:2]  python-protonvpn-nm-lib-3.8.0-1  protonvpn-cli-3.11.1-1

  2 python-protonvpn-nm-lib          (Build Files Exist)
  1 protonvpn-cli                    (Build Files Exist)
==> Packages to cleanBuild?
==> [N]one [A]ll [Ab]ort [I]nstalled [No]tInstalled or (1 2 3, 1-3, ^4)
==> 
:: PKGBUILD up to date, Skipping (2/0): python-protonvpn-nm-lib, protonvpn-cli
  2 python-protonvpn-nm-lib          (Build Files Exist)
  1 protonvpn-cli                    (Build Files Exist)
==> Diffs to show?
==> [N]one [A]ll [Ab]ort [I]nstalled [No]tInstalled or (1 2 3, 1-3, ^4)
==> 
:: (1/2) Parsing SRCINFO: python-protonvpn-nm-lib
:: (2/2) Parsing SRCINFO: protonvpn-cli

==> Making package: protonvpn-cli 3.11.1-1 (Sat 23 Apr 2022 04:48:46 PM +06)
==> Retrieving sources...
  -> Found 3.11.1.tar.gz
==> Validating source files with sha256sums...
    3.11.1.tar.gz ... ==> Making package: python-protonvpn-nm-lib 3.8.0-1 (Sat 23 Apr 2022 04:48:47 PM +06)
Passed
==> Retrieving sources...
  -> Found 3.8.0.tar.gz
==> Validating source files with sha256sums...
    3.8.0.tar.gz ... Passed
==> Making package: python-protonvpn-nm-lib 3.8.0-1 (Sat 23 Apr 2022 04:48:50 PM +06)
==> Checking runtime dependencies...
==> Checking buildtime dependencies...
==> Retrieving sources...
  -> Found 3.8.0.tar.gz
==> Validating source files with sha256sums...
    3.8.0.tar.gz ... Passed
==> Removing existing $srcdir/ directory...
==> Extracting sources...
  -> Extracting 3.8.0.tar.gz with bsdtar
==> Sources are ready.
==> Making package: python-protonvpn-nm-lib 3.8.0-1 (Sat 23 Apr 2022 04:48:56 PM +06)
==> Checking runtime dependencies...
==> Checking buildtime dependencies...
==> WARNING: Using existing $srcdir/ tree
==> Removing existing $pkgdir/ directory...
==> Starting build()...
Traceback (most recent call last):
  File "/home/golam/.cache/yay/python-protonvpn-nm-lib/src/protonvpn-nm-lib-3.8.0/setup.py", line 3, in <module>
    from setuptools import find_packages, setup
  File "/usr/lib/python3.10/site-packages/setuptools/__init__.py", line 18, in <module>
    from setuptools.dist import Distribution
  File "/usr/lib/python3.10/site-packages/setuptools/dist.py", line 32, in <module>
    from more_itertools import unique_everseen
ImportError: cannot import name 'unique_everseen' from 'more_itertools' (/usr/lib/python3.10/site-packages/more_itertools/__init__.py)
==> ERROR: A failure occurred in build().
    Aborting...
 -> error making: python-protonvpn-nm-lib
```

**Comment by Golam-moula** [comment]
bruh
