### ISSUE TITLE
[Enhancement] Provide option for ignoring IPv6

### ISSUE THREAD

**Issue by KSmanis** [ProtonVPN/linux-cli#76]
I sport a Gentoo system where I have globally disabled IPv6 (i.e., no `ipv6` kernel module and all packages are stripped of any IPv6 functionality with `USE=-ipv6`). Since v2.2.0 I can no longer use protonvpn-cli on my IPv6-less system:

```
# protonvpn c -f
Connecting to NL-FREE#2 via UDP...
Traceback (most recent call last):
  File "/root/.venvs/pvpn/bin/protonvpn", line 11, in <module>
    sys.exit(main())
  File "/root/.venvs/pvpn/lib64/python3.6/site-packages/protonvpn_cli/cli.py", line 73, in main
    cli()
  File "/root/.venvs/pvpn/lib64/python3.6/site-packages/protonvpn_cli/cli.py", line 116, in cli
    connection.fastest(protocol)
  File "/root/.venvs/pvpn/lib64/python3.6/site-packages/protonvpn_cli/connection.py", line 164, in fastest
    openvpn_connect(fastest_server, protocol)
  File "/root/.venvs/pvpn/lib64/python3.6/site-packages/protonvpn_cli/connection.py", line 504, in openvpn_connect
    manage_ipv6("disable")
  File "/root/.venvs/pvpn/lib64/python3.6/site-packages/protonvpn_cli/connection.py", line 658, in manage_ipv6
    stdout=subprocess.PIPE)
  File "/usr/lib64/python3.6/subprocess.py", line 423, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/usr/lib64/python3.6/subprocess.py", line 729, in __init__
    restore_signals, start_new_session)
  File "/usr/lib64/python3.6/subprocess.py", line 1364, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'ip6tables-save': 'ip6tables-save'
```

This functionality was introduced in commit 95701b0bd5b4785da254f35165c9db943b26b950

It would be awesome if there was a way to disable IPv6 functionality, either through a config key or a command-line argument.

Happy to help with more info and/or the implementation if you decide on a design.

**Comment by Rafficer** [comment]
Yeah... Just thinking if it should be another option in the `configure` menu or detect it automatically, which should be fairly easy (`which ip6tables`). I'm leaning more towards the second approach.

One more question: Why did you do that?

**Comment by KSmanis** [comment]
> One more question: Why did you do that?

Minimalism I guess, Gentoo is all about choice.

Let me know if you need any help!

**Comment by sanderdekoning** [comment]
I am running into the same issue while trying to run on MacOS 10.15.1 - is there any way I can resolve this error?

**Comment by KSmanis** [comment]
As of v2.2.3 the issue has been resolved for me. Thank you @Rafficer!
