### ISSUE TITLE
Possible Aur Build Issue

### ISSUE THREAD

**Issue by gsilvers** [ProtonVPN/linux-cli#76]
>  We are happy to answer your questions about the code or discuss technical ideas. 
 
Please complete the following checklist (by adding [x]):
- [X] I have searched open and closed issues for duplicates 
         Checked around not seeing this in any other open issues
- [X] This isn't a feature request
- [X] This is not a report about my app not working as expected

----------------------------------------

Hi Guys,

I'm digging more but it appears there is some sort of issue with your package for AUR/Manjaro/Arch. I have pyenv installed with several versions of python and the latest xdg regardless of which version I tried (3.8.13, 3.10.1, 3.10.4) seems to be getting this error:

==> Removing existing $pkgdir/ directory...
==> Starting build()...
Traceback (most recent call last):
  File "setup.py", line 5, in <module>
    from protonvpn_nm_lib.constants import APP_VERSION
  File "/var/tmp/pamac-build-gsilvers/python-protonvpn-nm-lib/src/protonvpn-nm-lib-3.10.0/protonvpn_nm_lib/constants.py", line 8, in <module>
    from xdg import BaseDirectory
ImportError: cannot import name 'BaseDirectory' from 'xdg' (/home/gsilvers/.pyenv/versions/3.8.13/lib/python3.8/site-packages/xdg/__init__.py)

Figured maybe my config was messing with it since I have many python versions but did not seem to make a difference. I was able to install by manually forcing PIP (worked under both 3.8 and 3.10) to install pyxdg manually before building your package. I'm not a package person but I'm guessing you're missing that requirement somewhere or something in your build does not play friendly with pyenv.

**Comment by gsilvers** [comment]
Yea not sure the best way for you to do this but in https://github.com/ProtonVPN/linux-app/blob/master/[Dockerfile.arch](https://github.com/ProtonVPN/linux-app/blob/master/Dockerfile.arch) It looks like you're relying on pacman to install python-xdg but if the user has pyenv and multiple python versions installed their current global pyenv will get hit up not the system python. Not sure if you can address this in your build but maybe you could put a note in the instructions saying IF you have pyenv installed you may need to install some packages manually in PIP?

**Comment by gsilvers** [comment]
Or maybe fakeroot? Let me know if I can help. As a work around users can manually pip the things in the file above.

**Comment by gsilvers** [comment]
Confirmed if I remove all pyenv from my shell it works. I would hope that the build script can ignore the pyenv

**Comment by gsilvers** [comment]
Yea guys going to close this, if you want to you can look into it. The basics of this are that pyenv and some aur installers including yours do not play well together. If the user follows https://github.com/[pyenv](https://github.com/pyenv/pyenv)/pyenv the installer will pick up the pyenv version of python from the bash profile rather than the system. I don't believe you should change the build scripts you have as I believe it would impact others as well. Using the system copy of python your installers all seem ok.
