### ISSUE TITLE
Not working on Debian 11

### ISSUE THREAD

**Issue by oqammx86** [ProtonVPN/linux-cli#80]
During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/protonvpn-cli", line 11, in <module>
    load_entry_point('protonvpn-cli==3.12.0', 'console_scripts', 'protonvpn-cli')()
  File "/usr/lib/python3/dist-packages/protonvpn_cli/main.py", line 21, in main
    ProtonVPNCLI()
  File "/usr/lib/python3/dist-packages/protonvpn_cli/cli.py", line 65, in __init__
    res = getattr(self, args.command)()
  File "/usr/lib/python3/dist-packages/protonvpn_cli/cli.py", line 162, in login
    return self.cli_wrapper.login(args.username)
  File "/usr/lib/python3/dist-packages/protonvpn_cli/cli_wrapper.py", line 63, in login
    if self.protonvpn.check_session_exists():
  File "/usr/lib/python3/dist-packages/protonvpn_nm_lib/api.py", line 356, in check_session_exists
    return self._env.api_session.is_valid
  File "/usr/lib/python3/dist-packages/protonvpn_nm_lib/core/environment.py", line 56, in api_session
    self.__api_session = APISession()
  File "/usr/lib/python3/dist-packages/protonvpn_nm_lib/core/session/session.py", line 224, in __init__
    self.__keyring_load_session()
  File "/usr/lib/python3/dist-packages/protonvpn_nm_lib/core/session/session.py", line 253, in __keyring_load_session
    keyring_data_user = ExecutionEnvironment().keyring[
  File "/usr/lib/python3/dist-packages/protonvpn_nm_lib/core/keyring/linuxkeyring.py", line 32, in __getitem__
    raise exceptions.KeyringError(e)
protonvpn_nm_lib.exceptions.KeyringError: Environment variable DBUS_SESSION_BUS_ADDRESS is unset

**Comment by HolyMacarony** [comment]
i have the very same issue on my RPI4. Have also not found a solution yet. Debian 10 worked flawless.

**Comment by sputnick-dev** [comment]
`DBUS_SESSION_BUS_ADDRESS` is unset, that means that you need `dbus` to run before.

On my LinuxMint:

```
$ echo $DBUS_SESSION_BUS_ADDRESS 
unix:path=/run/user/1000/bus
```
and :

```
$ ps auxwww | grep dbus
message+    1126  0.0  0.0  11332  4584 ?        Ss   mai11   1:28 @dbus-daemon --system --address=systemd: --nofork --nopidfile --systemd-activation --syslog-only
stardust    1768  0.0  0.0  17876 10408 ?        Ss   mai11   4:20 /usr/bin/dbus-daemon --session --address=systemd: --nofork --nopidfile --systemd-activation --syslog-only
stardust    1899  0.0  0.0   9248  2016 ?        S    mai11   0:09 /usr/bin/dbus-daemon --config-file=/usr/share/defaults/at-spi2/accessibility.conf --nofork --print-address 11 --address=unix:path=/run/user/1000/at-spi/bus_0
```
