### ISSUE TITLE
Unable to connect with kill switch enabled

### ISSUE THREAD

**Issue by dokutan** [ProtonVPN/linux-cli#81]
Sometimes connecting with the kill switch enabled fails with this error:
```
Setting up ProtonVPN.
dbus[3204]: arguments to dbus_message_iter_append_basic() were incorrect, assertion "_dbus_check_is_valid_path (*string_p)" failed in file dbus-message.c line 2776.
This is normally a bug in some application using the D-Bus library.

ERROR:dbus.connection:Unable to set arguments ('/org/freedesktop/NetworkManager/Settings/12', 'None', '/') according to signature 'ooo': <class 'MemoryError'>:
ERROR:protonvpn-cli:
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/protonvpn_cli/cli_wrapper.py", line 277, in connect
    self.protonvpn.setup_connection(
  File "/usr/lib/python3.10/site-packages/protonvpn_nm_lib/api.py", line 153, in setup_connection
    self._env.connection_backend.setup(**data)
  File "/usr/lib/python3.10/site-packages/protonvpn_nm_lib/core/connection_backend/nm_client/nm_client.py", line 81, in setup
    self._pre_setup_connection(kwargs.get("entry_ip"))
  File "/usr/lib/python3.10/site-packages/protonvpn_nm_lib/core/connection_backend/nm_client/nm_client.py", line 235, in _pre_setup_connection
    killswitch.manage(
  File "/usr/lib/python3.10/site-packages/protonvpn_nm_lib/core/killswitch/killswitch.py", line 82, in manage
    actions_dict = {
  File "/usr/lib/python3.10/site-packages/protonvpn_nm_lib/core/killswitch/killswitch.py", line 185, in setup_pre_connection_ks
    self.activate_connection(self.ks_conn_name)
  File "/usr/lib/python3.10/site-packages/protonvpn_nm_lib/core/killswitch/killswitch.py", line 422, in activate_connection
    active_conn = self.nm_wrapper.activate_connection(
  File "/usr/lib/python3.10/site-packages/protonvpn_nm_lib/core/dbus/dbus_network_manager_wrapper.py", line 154, in activate_connection
    active_conn_path = nm_interface.ActivateConnection(
  File "/usr/lib/python3.10/site-packages/dbus/proxies.py", line 72, in __call__
    return self._proxy_method(*args, **keywords)
  File "/usr/lib/python3.10/site-packages/dbus/proxies.py", line 141, in __call__
    return self._connection.call_blocking(self._named_service,
  File "/usr/lib/python3.10/site-packages/dbus/connection.py", line 643, in call_blocking
    message.append(signature=signature, *args)
MemoryError

An unknown error has occured. Please ensure that you have internet connectivity.
If the issue persists, please contact support.
```

There are two workarounds i know of:
1. Disable the kill switch (meybe not desirable)
2. Manually delete the network interfaces created by the VPN:
```
sudo ip link delete pvpnksintrf0
sudo ip link delete ipv6leakintrf0
```

**Comment by papamoose** [comment]
I'm also not able to connect with killswitch enabled on Ubuntu 22.04 using Network Manager.

```
$ protonvpn-cli ks --on
Kill switch has been enabled. Please reconnect to VPN to activate it.
```
```
$ protonvpn-cli c --cc us
Setting up Proton VPN.
dbus[237967]: arguments to dbus_message_iter_append_basic() were incorrect, assertion "_dbus_check_is_valid_path (*string_p)" failed in file ../../../dbus/dbus-message.c line 2765.
This is normally a bug in some application using the D-Bus library.

  D-Bus not built with -rdynamic so unable to print a backtrace
Aborted (core dumped)
```

**Comment by glenn6h** [comment]
Can confirm it's not working. Current workaround is to disable killswitch then connect.

**Comment by ItsQuadrus** [comment]
Can confirm too, this is kinda funny.

**Comment by invisiblegaudi** [comment]
Confirming, getting following error after starting gui via cli and clicking kill switch button on gui
 ```
 dbus[104838]: arguments to dbus_message_iter_append_basic() were incorrect, assertion "_dbus_check_is_valid_path (*string_p)" failed in file ../../../dbus/dbus-message.c line 2765.
This is normally a bug in some application using the D-Bus library.

  D-Bus not built with -rdynamic so unable to print a backtrace
Aborted (core dumped)
```
incredibly frustrating as connection continually drops (on Ubuntu 22.04.2 LTS)
I must constantly check that I am protected and manually reconnect.
I regularly find that I have been exposing my IP unbeknownst to myself

**Comment by MKoesters** [comment]
I still have the same problem.
Will this be fixed soon?
