### ISSUE TITLE
Login errors in Ubuntu 22.04

### ISSUE THREAD

**Issue by ae33** [ProtonVPN/linux-cli#97]
Hello,

I have installed the the ProtonVPN CLIs and GUIs in MacOS, Arch Linux and Ubuntu 22.04. I have not had any login issues with either the MacOS or Arch Linux versions. However, when I try to execute a `protonvpn-cli login <username>` command, I get the following error after I enter my password:
```
Unknown error occured. If the issue persists, please contact support.
```
The error message I see is the same whether or not I enter the correct password. I can connect to the internet, just fine, in all of my other applications (including running a `ping google.com` command from the same terminal), so I don't believe it to be a network issue.

**Comment by Wilhelmvon** [comment]
Same issue here, first I was already logged and when I tried to connect using **protonvpn-cli c** I had this error:

`2023-03-20 16:46:49,414 — cli.py — INFO — __init__:29 — Proton VPN CLI v3.13.0 (protonvpn-nm-lib v3.14.0; proton-client v0.7.1)
2023-03-20 16:46:49,424 — cli.py — INFO — __init__:64 — CLI command: Namespace(command='r', version=False, help=False, get_logs=False)
2023-03-20 16:46:52,336 — cli_wrapper.py — ERROR — reconnect:419 — Invalid refresh token
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/protonvpn_nm_lib/core/session/session.py", line 39, in __call__
    result = self._func(session, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/protonvpn_nm_lib/core/session/session.py", line 620, in update_servers_if_needed
    self.__proton_api.api_request(
  File "/usr/lib/python3/dist-packages/proton/api.py", line 294, in api_request
    raise ProtonAPIError(response)
proton.exceptions.ProtonAPIError: Invalid access token

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/protonvpn_nm_lib/core/session/session.py", line 39, in __call__
    result = self._func(session, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/protonvpn_nm_lib/core/session/session.py", line 411, in refresh
    self.__proton_api.refresh()
  File "/usr/lib/python3/dist-packages/proton/api.py", line 468, in refresh
    refresh_response = self.api_request(
  File "/usr/lib/python3/dist-packages/proton/api.py", line 294, in api_request
    raise ProtonAPIError(response)
proton.exceptions.ProtonAPIError: Invalid refresh token

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/protonvpn_cli/cli_wrapper.py", line 417, in reconnect
    self.protonvpn.setup_reconnect()
  File "/usr/lib/python3/dist-packages/protonvpn_nm_lib/api.py", line 344, in setup_reconnect
    return self.setup_connection(
  File "/usr/lib/python3/dist-packages/protonvpn_nm_lib/api.py", line 125, in setup_connection
    server = connect_configurations[connection_type](
  File "/usr/lib/python3/dist-packages/protonvpn_nm_lib/api.py", line 280, in config_for_server_with_servername
    return self._env.api_session.servers.filter(
  File "/usr/lib/python3/dist-packages/protonvpn_nm_lib/core/session/session.py", line 675, in servers
    self.update_servers_if_needed()
  File "/usr/lib/python3/dist-packages/protonvpn_nm_lib/core/session/session.py", line 42, in __call__
    self.__handle_api_error(e, session, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/protonvpn_nm_lib/core/session/session.py", line 69, in __handle_api_error
    return getattr(
  File "/usr/lib/python3/dist-packages/protonvpn_nm_lib/core/session/session.py", line 154, in _handle_401
    session.refresh()
  File "/usr/lib/python3/dist-packages/protonvpn_nm_lib/core/session/session.py", line 42, in __call__
    self.__handle_api_error(e, session, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/protonvpn_nm_lib/core/session/session.py", line 69, in __handle_api_error
    return getattr(
  File "/usr/lib/python3/dist-packages/protonvpn_nm_lib/core/session/session.py", line 207, in _handle_10013
    raise APISessionIsNotValidError(error)
protonvpn_nm_lib.exceptions.APISessionIsNotValidError: Invalid refresh token
2023-03-20 16:47:06,098 — cli.py — INFO — __init__:17 —`

Then I logout with **protonvpn-cli logout** and when trying to login again with **protonvpn-cli login <proton-user>**, I saw this:

`Unknown error occured. If the issue persists, please contact support.`

**Comment by Wilhelmvon** [comment]
Same issue here, first I was already logged and when I tried to connect using **protonvpn-cli c** I had this error:

> 2023-03-20 16:46:49,414 — cli.py — INFO — __init__:29 — Proton VPN CLI v3.13.0 (protonvpn-nm-lib v3.14.0; proton-client v0.7.1)
> 2023-03-20 16:46:49,424 — cli.py — INFO — __init__:64 — CLI command: Namespace(command='r', version=False, help=False, get_logs=False)
> 2023-03-20 16:46:52,336 — cli_wrapper.py — ERROR — reconnect:419 — Invalid refresh token
> Traceback (most recent call last):
>   File "/usr/lib/python3/dist-packages/protonvpn_nm_lib/core/session/session.py", line 39, in __call__
>     result = self._func(session, *args, **kwargs)
>   File "/usr/lib/python3/dist-packages/protonvpn_nm_lib/core/session/session.py", line 620, in update_servers_if_needed
>     self.__proton_api.api_request(
>   File "/usr/lib/python3/dist-packages/proton/api.py", line 294, in api_request
>     raise ProtonAPIError(response)
> proton.exceptions.ProtonAPIError: Invalid access token
>  
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/usr/lib/python3/dist-packages/protonvpn_nm_lib/core/session/session.py", line 39, in __call__
>     result = self._func(session, *args, **kwargs)
>   File "/usr/lib/python3/dist-packages/protonvpn_nm_lib/core/session/session.py", line 411, in refresh
>     self.__proton_api.refresh()
>   File "/usr/lib/python3/dist-packages/proton/api.py", line 468, in refresh
>     refresh_response = self.api_request(
>   File "/usr/lib/python3/dist-packages/proton/api.py", line 294, in api_request
>     raise ProtonAPIError(response)
> proton.exceptions.ProtonAPIError: Invalid refresh token
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/usr/lib/python3/dist-packages/protonvpn_cli/cli_wrapper.py", line 417, in reconnect
>     self.protonvpn.setup_reconnect()
>   File "/usr/lib/python3/dist-packages/protonvpn_nm_lib/api.py", line 344, in setup_reconnect
>     return self.setup_connection(
>   File "/usr/lib/python3/dist-packages/protonvpn_nm_lib/api.py", line 125, in setup_connection
>     server = connect_configurations[connection_type](
>   File "/usr/lib/python3/dist-packages/protonvpn_nm_lib/api.py", line 280, in config_for_server_with_servername
>     return self._env.api_session.servers.filter(
>   File "/usr/lib/python3/dist-packages/protonvpn_nm_lib/core/session/session.py", line 675, in servers
>     self.update_servers_if_needed()
>   File "/usr/lib/python3/dist-packages/protonvpn_nm_lib/core/session/session.py", line 42, in __call__
>     self.__handle_api_error(e, session, *args, **kwargs)
>   File "/usr/lib/python3/dist-packages/protonvpn_nm_lib/core/session/session.py", line 69, in __handle_api_error
>     return getattr(
>   File "/usr/lib/python3/dist-packages/protonvpn_nm_lib/core/session/session.py", line 154, in _handle_401
>     session.refresh()
>   File "/usr/lib/python3/dist-packages/protonvpn_nm_lib/core/session/session.py", line 42, in __call__
>     self.__handle_api_error(e, session, *args, **kwargs)
>   File "/usr/lib/python3/dist-packages/protonvpn_nm_lib/core/session/session.py", line 69, in __handle_api_error
>     return getattr(
>   File "/usr/lib/python3/dist-packages/protonvpn_nm_lib/core/session/session.py", line 207, in _handle_10013
>     raise APISessionIsNotValidError(error)
> protonvpn_nm_lib.exceptions.APISessionIsNotValidError: Invalid refresh token
> 2023-03-20 16:47:06,098 — cli.py — INFO — __init__:17 —
> 

Then I logout with **protonvpn-cli logout** and when trying to login again with **protonvpn-cli login user@proton**, I saw this:

`Unknown error occured. If the issue persists, please contact support.`

**Comment by Nathan-Shea** [comment]
I'm also having this problem on two different computers. Two different distros as well.

**Comment by neuron303** [comment]
To me this looks like a duplicate of https://github.com/ProtonVPN/linux-cli/issues/19.
At least it was in my case and the solution was to verify the permissions in ~/.gnupg and make sure that $GNUPGHOME is not set (because the client is hardcoded to that path apparently).
Would be nice to get a more specific error message and have better handling of gnupg.
